### ISSUE TITLE
Custom liveness/readiness probes are not being created

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1019]
The plugin should be already configured to create liveness/readiness probes from custom user definition, as in the following example:

```
<resources>
   <readiness>
      <getUrl>/monitor/</getUrl>
   </readiness>
</resources>
```

Anyway no probes seem to be generated by this configuration.
We should:
- fix the issue (see discussion in #1014)
- create an integration test to avoid regression
- document the feature in the doc

**Comment by cescoffier** [comment]
@nicolaferraro I'm not sure the current config model does not support nested structure. See my other PR where I'm using the Maven configuration directly.

Right now, this does not work because the `ResourceConfig` does not have the readiness and liveness attributes (io.fabric8.maven.core.config.ResourceConfig:100).

**Comment by rhuss** [comment]
@nicolaferraro you are right we should value XML configuration over enricher config when reconsidering the XML configuration in #18 

@cescoffier afais this issue is about the XML config syntax in general, not for a an enricher config. Nevertheless we are thinking about a deeper configuration for enrichers via #1375
