### ISSUE TITLE
Revert default image name back to "latest" for snapshots

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1093]
Using timestamps as tags breaks so often, especially when running `fabric8:resource` and `fabric8:build` in different invocations of Maven (where different timestamps are calculated). Also it turned out that in the recent versions even when using `mvn fabric8:resource fabric8:build` it does work, but for `mvn fabric8:build fabric8:resource` the timestamp of the image is different then created in the resource files.

This is so fragile that at least for the default I would revert back to `%g/%a:%l` in

https://github.com/fabric8io/fabric8-maven-plugin/blob/76ee023bd976b246d64715d6f063fad1a0208718/generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java#L194

Other issues are the excessive creation of Docker images (which needs to be cleaned up manually). For me updating existing images also works without using timestamps, so I really would reconsider the original use case for using a timestamp as tag. And maybe consider to implement a different solution.

**Comment by giannello** [comment]
We're currently facing the same issue. We don't specify a tag in the image `<name>`, as the default behaviour of using `latest` for snapshot builds is fine, and we specify a proper tag, as `[timestamp]-[commit hash]` in the `<tags>` section.
the `fmp-controller` enricher generates a deployment with `latest` as image tag, but specifying a different tag in the image configuration works only when running the full deploy lifecycle, as some specific properties are otherwise not set. Also, as addressed by this issue, the timestamp changes, so multiple use-cases like `fabric8:start`/`fabric8:watch` and their d-m-p companions are broken.
A workaround would be to store those properties in a file and load them on subsequent maven invocations, but I would really like to avoid having stateful maven builds. I'm planning to implement a quick fix to `fmp-enricher` to add an option to override the image tag regardless of the <image> settings.

**Comment by piyush1594** [comment]
Hey @rhuss @giannello 

I tried all the goals(separate and in a single hit) in minikube after doing the changes as suggested by you (Changing the timestamp to latest) 

All the goals work fine after doing the change. The application gets properly deployed after doing the change. Also the excessive generation of the images which gets generated after every hit of `fabric8: build` also get resolved because it just removes the previous image and stores the new image with `latest` tag. The resource also gets generated with latest tag and application get deployed every time.

I think this resolves the problem of invocations broken. Should we consider this workaround of changing timestamp to the latest or any other solution is in your mind regarding this like generating images always with the name of tag mentioned in the resource file. This will break `fabric8: build fabric8: resource` order. If we always create a resource with the tag last created then `fabric8: resource fabric8: build fabric8: deploy` will deploy the old image. Right now, only this changing to latest looking fine to me. It solving both invocations and excessive generation.

Please suggest if other workarounds can be done for this.

cc @hrishin @rohanKanojia 

Thanks

**Comment by rhuss** [comment]
I think the simplest workaround is really to change the default only, as you correctly mentioned that timestamp based correlation between images and resource descriptors is not guaranteed and depends on the order of goals called.

But people could still try to reuse the timestamp based approach if the want to. 

The only drawback is that after a redeployment some old images can't be removed when building because the might be still in use (there will be a warning in the output).

I proposed a solution some times ago for this which was a bit involved (and which I would have to look up in the history), but I think even with the warning this is the better solution.

**Comment by rhuss** [comment]
Found the issue about the original motivation and the proposed solution --> https://github.com/fabric8io/fabric8-maven-plugin/issues/77#issuecomment-223509254

**Comment by rhuss** [comment]
Please dont add _yet another flag_. I think the patterns which can be used as image names should be completely enough.

Actually I tried hard early 2017 to get rid of all the random properties to come to a more concise configuration model. Its so easy to add random properties, which are, btw, not all typesafe and completely ignored when mistyped. I was not 100% successful before I had to stop, though. Adding back properties to support very specific use cases however feels for me to be the wrong direction.
