### ISSUE TITLE
build timeout for OpenShift build service

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1133]
### Description
Sometimes the OpenShift build service gives timeout: Socket closed error.
 ```[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.30:build (fmp) on project spring-boot-rest-http-crud: Failed to execute the build: Unable to build the image using the OpenShift build service: An error has occurred. timeout: Socket closed -> [Help 1]```

This issue is observed mostly in the regression test environment having single node OpenShift cluster spin up using `oc cluster up`

### Info
may be related to #1016

* f-m-p version : v3.5.30 
* Maven version (`mvn -v`) :Apache Maven 3.3.9
```

```
* Kubernetes / OpenShift setup and version : V3.6.0, V3.6.1 (single node clusters)
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@hrishin : I ran the build 50 times on Travis CI but was unable to reproduce this error. Out of 50 times build failed only once(which was due to some Image Build error); You can have a look at all the build logs [here](https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/builds). I found one [issue](https://github.com/openshiftio/openshift.io/issues/1537) related to same `Socket Closed` error, but they concluded that it was a CI issue.
