### ISSUE TITLE
Fix CI setup of fabric8 maven plugin

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1198]
Since we enabled Openshift 3.7 on Travis CI, we were facing lots of issues on Travis due to extremely slow regression tests and they were getting timeout because by default Travis gives a job a maximum time limit of 50 minutes to run. For more information see [here](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts).

So due to this, we switched to CircleCI in the meantime. But now the build timeout limit of Travis has been extended; So we should revert back to Travis CI.

**Comment by piyush1594** [comment]
CI is not working because of VertxHTTPBooster. The test is locally working fine for me but on CI it is failing because of Pod Timeout every time. This may be because of some changes in the booster or maybe in Openshift because it was working fine previously or may be in FMP as we are checking current master. For the time being, tests are failing and are are blockers for PR merging.

@rohanKanojia Just an initial thought, can you check with a released version in spite of FMP master, if this works then it will help in eliminating one condition that it is breaking because of FMP changes.

Also, can you please check by simple running only this booster in place of all 6 boosters to find out that if this is because of resource issue on CI.

I may be wrong on some thoughts, but we need to get it fixed soon.
