### ISSUE TITLE
fabric8:debug ignores pod's namespace 

### ISSUE THREAD

**Issue by gintautassulskus** [fabric8io/fabric8-maven-plugin#1266]
### Description
Command `fabric8:debug` always references a pod in the `default` namespace.
The [commad line](https://github.com/fabric8io/fabric8-maven-plugin/blob/d3c808295fe9e06c6a8f78af4edd16cff13fdbb4/core/src/main/java/io/fabric8/maven/core/service/PortForwardService.java#L244) is missing `-n <namespace>` argument.

### Info
* f-m-p version: 3.5.38

**Comment by rohanKanojia** [comment]
Yes, need to append namespace option here: https://github.com/fabric8io/fabric8-maven-plugin/blob/09614b231884b43d2e868aeec446cf7d1b26acab/core/src/main/java/io/fabric8/maven/core/service/PortForwardService.java#L236-L245

**Comment by dev-gaur** [comment]
ping @rhuss

**Comment by rohanKanojia** [comment]
@gintautassulskus: I agree with @dev-gaur here. I misunderstood it a bit.. As far as I know we don't support debugging in namespaces other than your current namespace,. `fabric8:debug` opens debug port so that you can debug the latest pod in the namespace you deployed(which is the default namespace you're logged into).

Would really appreciate if you could elaborate what problem exactly are you facing?

**Comment by gintautassulskus** [comment]
@rohanKanojia, thanks for clarifying. I must have misunderstood the behaviour hence the raised issue. I will close the case.
