### ISSUE TITLE
when merging a service.yml with the default generated service; lets only take the first port

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#144]
as multiple ports don't work on OpenShift

**Comment by rhuss** [comment]
@jstrachan I just hit an issue with this fix. Is this still true that multi port services don't work on OpenShift ? I cannot find any reference why it should not work. I know we had some issue at that time, but I can't remember anymore.

@jimmidyson do you know if multiport services have issue on OpenShift ? I know for routes that you can't map [to different ports with the same path](http://stackoverflow.com/questions/42373477/q-service-with-multiple-ports-protocols-per-route-e-g-http-and-https-possibl), but that should not be an issue for the services. 

Also found https://github.com/openshift/origin/issues/4603 but don't know whether its related.

I ask because I would like to reenable multi-port services. I'm working on the `DefaultServiceEnricher` and the XML configuration for services so it's quite unexpected for a user if he configures multiple ports for a service in XML but only the first is really taken.

**Comment by rhuss** [comment]
Also related to this commit https://github.com/fabric8io/fabric8-maven-plugin/commit/60801ee91dbe3c6e07ac1542cd7a2e08a46f4bc5

**Comment by rhuss** [comment]
Even when a services has more than one port, doesn't mean that we have to create routes for all those ports. If this a restriction on the route only, I'd prefer to add this restriction when we create routes. 

Also the `exposecontroller` can decide to expose only the first port for a multi-port service.

I can understand the restriction wrt. routing, but working around this on the service level is wrong imo (as it might still make sense to have cluster internal services with multiple ports)

**Comment by jstrachan** [comment]
@rhuss I agree - now OpenShift Routes support multiple ports; so we should be able to stick with 1 `Service` and 1 `Route` with multiple ports going forward which will be much simpler - it will also display nicer in the openshift console ;)

**Comment by jstrachan** [comment]
The 'first port' export stuff was basically a hack to get things working on openshift when it only supported 1 port per route - we should do things properly now though

**Comment by rhuss** [comment]
@jstrachan thanks!

I'm just reworking the enricher and found a nice backwards compatible way to support multi ports (disabled by default) and a more flexible mapping on enricher level. I also will add some more documentation and hopefully can add a full XML support.

**Comment by jstrachan** [comment]
awesome thanks! Its on my list of things to do to go around the fabric8 ecosystem and move to multi-port services + routes (e.g. jenkins / gogs et al) so I can test our your changes in a week or two when I get there

**Comment by rhuss** [comment]
@jstrachan I updated the service enricher with #923 now , documentation has been added, too: https://github.com/rhuss/fabric8-maven-plugin/blob/pr/default-service-enricher-refactor/doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc

I think the port mapping is now quite flexible, for multi- and non multi-port cases. 'hope it doesnt break too much ;-)
