### ISSUE TITLE
customizer to auto-detect executable jars OOTB

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#146]
if we have an executable jar we should default the docker command accordingly without the user having to add any explicit configuration. Also if we have a vanilla executable jar (without Spring Boot or WF Swarm) we should enable the docker image being created; using artifact-with-dependencies etc.

e.g. this example https://github.com/fabric8-quickstarts/vertx-simple should not require the main class to be provided in the fabric8-maven-plugin configuration since it can be deduced/used via the executable jar.

This issue is similar to #143 and this example https://github.com/fabric8-quickstarts/swarm-camel though with WF Swarm its also a fat jar too

To deal with executable jars versus Spring Boot versus WF Swarm; we may need a way to prioritise customerisers; e.g. Spring Boot customisation before 'executable jar' customisation?

**Comment by rhuss** [comment]
Technically you can already prioritise customisers / enrichers by adding an order in the `fabric8-default-customizers` manfifest. It's just a matter of the order.

We could also add a sort of `break` method in the Customizer interface, which stops looking into customizer further down. E.g. when a spring boot customizer has detected to run then it could stop any other customization (which could break things).

The plain java app customizer could detect the main  class:

* Checking the source for a `public void static main()` and when it founds a unique one, take this.
* Check for a `maven-execute-pluging` config and use a main class from there

For `spring-boot` and `widlfly-swarm` we should not need to extract a main class at all, as the base image should be able to start this without the need of a main class.

btw, I really like to move 'customizer' to 'starter' ;-)

**Comment by rhuss** [comment]
I added support for auto-detection of a Main-Class in `target/classes`.

However, this wont found MainClasses from dependencies, like `org.apache.camel.cdi.Main`.
I wonder whether we should add some sort of white-list to detect these classes, too ? Or we could even add a dedicated **Camel** detector.

**Comment by jstrachan** [comment]
Yeah, thats not a bad idea really. Though I guess its not a biggie to have custom configuration for the main in cases where we're not producing an executable jar

**Comment by rhuss** [comment]
Ok. My next steps here are:

* Auto-detect 'fat' jars. E.g. by checking for the maven-shade-plugin or even examining the jars below `target/` by reading their manifest. This would also adapt the assembly configuration to include this jar, which would be nice because it will work with wildfly-swarm, too (wildfly-swarm is a bit unorthodox as it doesn't add its repackaged jar to the reactor, like e.g. spring-boot)

* Add an option to d-m-p to write out a classpath file (much like hawt-app plugin). This option then can be switched on by the `java-exec` generator so that we also have nice classpath ordering (because the base image can take benefit from this classpath file).

* Ensure that the spring-boot-generator and the java-exec-generator don't interfere. By default, that wont happen, because when spring-boot runs first, then there is already an image configuration created when the java-exec generartor runs so this won't kick in, except when 'combine' is enabled. In that case we would need to have some trigger, that the image configuration contains a auto-generated image. Maybe we should reserve an image label like 'f8.generator' which we always fill with the generator name which generated this image ? That way a later generator can examine the image list for such a label and does not run when it already a generated image.

**Comment by kameshsampath** [comment]
will be a good idea to add another generator dedicated for vertx and then use it to enrich vertx specific thing ?

http://vertx.io/docs/vertx-docker/

**Comment by jstrachan** [comment]
agreed. If a vertx project is using an executable jar then the current executable jar generator should be usable really; its more for things like service port detection we need the vertx specific enricher; unless there's a different approach in vertx to a vanilla executable jar

**Comment by kameshsampath** [comment]
my thoughts, if we use a dedicated vertx-generator, then we can provide config option to the user where he can add the config file i.e. the ones used as part of -conf for the vertx, we can parse that json to find out the ports to be exposed provides the user provides a property like `http.port` or something else .. if we dont find anything we default to `8080`

**Comment by rhuss** [comment]
I'm currently on it (sorry was distracted by a conference week), but I brought back some ideas from the vert.x f2f meeting, like detecting whether a maven-shade-plugin is configured for a vert.x app and how to detect liveness and readiness checks based on the inclusion of the dependency vertix-dropwizward-metrics.

Unfotunately for the port there is no solution since vert.x apps set the port programmtically and do not have a common configuration mechanism like spring-boot.

**Comment by rhuss** [comment]
@kameshsampath afaik there is nothing like a universally valid configuration syntax for vertx apps ;-(. Would be good to have this, though (as well as for wildfly-swarm)

**Comment by rhuss** [comment]
Another idea is to introduce a lightweight vertx-maven-plugin which does the packaging. The maven-shader-plugin config is quite ugly and lengthy, so this could be shorten down to five lines (like the spring-boot-plugin).

Also, this plugin together maybe with an extra vertx-module could provide the missing application properties features. But thats probably more a long term goal.

**Comment by kameshsampath** [comment]
@rhuss do you want me to start working on vertx-generator, once you are back you can review and  we could polish it further

**Comment by rhuss** [comment]
@kameshsampath could you hold on a bit ? I already started and have a skeleton, just need to polish it and push. Think I can do it tomorrow.

**Comment by rhuss** [comment]
Or maybe later on the plane. You then could take it over ;-)

**Comment by kameshsampath** [comment]
however you want me to, let me know once you want me to take it forward , then i will work on it

**Comment by rhuss** [comment]
A lot of things have been changed since then. I think we can safely close this and open a new issues. But for fat jar I think we are really in good shape.
