### ISSUE TITLE
Rebranding fmp

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1479]
Rebranding suggestion for fmp:

* Two plugins for OpenShift & Kubernetes
* Using a neutral repository name (tbd, idea welcome !)
* Use a “openshift-maven-plugin” (or “okd-maven-plugin” ?) with a “okd:” prefix
 “kubernetes-maven-plugin” with “k8s:” prefix
* Let kubernetes-maven-plugin create only a `kubernetes.yaml` but `openshift-maven-plugin` include `kubernetes.yml` and `openshift.yml`
* Skip all fabric8 naming

**Comment by rohanKanojia** [comment]
Okay, so we're considering to shift to this repository : https://github.com/jshiftio

So in order to begin movement/rebranding, I see these two approaches:

- Move fabric8 maven plugin repository to jshift (transfer ownership) and then refactor in order to abstract openshift-maven-plugin, jshift-kit etc out of it afterwards.
- Maintain fabric8-maven-plugin here in this org, and start these projects from scratch(kubernetes-maven-plugin, openshift-maven-plugin, jshift-kit) and give a link in readme that fmp is gonna get depracated soon and use these new plugins. This would require having a new clean start :-) 

@rhuss @lordofthejars @dev-gaur Please share your thoughts?

**Comment by rhuss** [comment]
I opt for the second options as this allows for a clean and fresh start. Moving bits and pieces individually might be more work, but also an occasion to get rid of legacy.

Also it makes it more evident that this is a clear cut.
