### ISSUE TITLE
Proposal to reduce boilerplate code

### ISSUE THREAD

**Issue by h3nrique** [fabric8io/fabric8-maven-plugin#1644]
I would like propose to use [Lombok](https://projectlombok.org/) to reduce boilerplate code in plugin project.

What do you think about?

**Comment by rohanKanojia** [comment]
@lordofthejars @dev-gaur What do you think about this?

**Comment by lordofthejars** [comment]
Hi, well I do not like very much Lombok because it relies on the class generation which means that `.java` files do not contain any getter/setter and then you run one Maven goal and the `.class` are generated with getters/setters and this is something I do not like because means that when I import the project into IDE I get compilation errors because there is no getter/setters in classes placed at `target` directory. Also at the very end, it is just getters and setters which are at the bottom of a class and can be autogenerated by IDE.

**Comment by h3nrique** [comment]
You are right. It's necessary configure IDE with plugin, but in command line `mvn build` is transparent.

I believe it's a low cost when compared to the amount of boilerplate code that can reduce.

**Comment by dev-gaur** [comment]
Should we close this thread? @lordofthejars @rohanKanojia
