### ISSUE TITLE
allow pod templates to be combined?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#17]
in terms of post processing of the rc.yml I can imagine folks wanting to add custom sidecar containers.

One specific example that just came up; there's an Infinispan Server RC.yaml which can be deployed as a remote service. However being a cache you often wanna colocate it inside a pod. So it might be nice to embed the infinispan server RC.yaml inside your apps pod template as another container. (i.e. it just copies the containers across and any volumes or secret annotations etc).

So might be nice to have some way to declaratively describe this operation; or maybe its a custom DSL builder thingy operation to merge in a sidecar container from some other RC yaml (described via mvn coordinates maybe?)

**Comment by jstrachan** [comment]
I guess this example shows how we can use the builder stuff to add custom containers:
https://github.com/jstrachan/fabric8-devops/blob/0de82b3b04b0b3c2d4c89b1668e1e9d795bc8c48/kibana/src/main/java/io/fabric8/apps/kibana/KibanaModelProcessor.java#L36-L36

we'd just need a way to load (maybe inject?) an RC via maven coordinates?

**Comment by rhuss** [comment]
Do you mean to extract the pod template from the infinispan server RC.yaml and include it into the list of containers for the app to create ?

If it is only about adding containers from other images (whose build is not managed by the pom.xml) to the set of containers for a pod, then this should be easily possible with the new configuration structure.

Since we include d-m-p which knows how to deal with multiple images in its configuration (originally intended for doing plain docker integration tests where other images needs to be started as deps), this can be added easily.

Currently I'm fiddling with the configuration syntax, will have a proposal and the end of the day.

Next steps is then to pick up external config files which can be 'enriched' like in https://github.com/fabric8io/fabric8-maven-plugin/blob/master/src/main/java/io/fabric8/maven/fabric8/enricher/impl/ProjectInfoEnricher.java

**Comment by jstrachan** [comment]
@rhuss yes thats exactly what I mean - being able to reuse in some app the container from a separate project's RC as a sidecar

**Comment by jstrachan** [comment]
another use case off the top of my head - being able to co-locate the APIman proxy gateway; or the fabric8 messaging gateway as a sidecar container in a pod. i.e. reuse a container from a separate maven project's RC.yml
