### ISSUE TITLE
Add generator and enricher for WildFly bootable JAR

### ISSUE THREAD

**Issue by jfdenise** [fabric8io/fabric8-maven-plugin#1819]
### Description

We are introducing a new way to run WildFly applications inside a bootable JAR starting WildFly 20. The maven plugin is defined there: https://github.com/wildfly-extras/wildfly-jar-maven-plugin

This plugin relies on [Galleon](https://github.com/wildfly/galleon) to indentify the server capabilities a user wants to see provisioned.

We have a need for:
*  A new generator (that extends java-exec) and disable both Prometheus and Jolokia. 
* A new HealthcheckEnricher to discover and configure Probes.

A WIP branch to highlight early work: https://github.com/jfdenise/fabric8-maven-plugin/tree/wildfly-jar

**Comment by manusa** [comment]
Hi @jfdenise,

FMP will be deprecated soon, all new features and enhancements are being provided by the core maintainer team in [Eclipse JKube](https://github.com/eclipse/jkube) repository.

WildFly Swarm [Generator](https://github.com/eclipse/jkube/blob/master/jkube-kit/generator/wildfly-swarm/src/main/java/org/eclipse/jkube/generator/wildflyswarm/WildFlySwarmGenerator.java) and also WildFly [webapp handler](https://github.com/eclipse/jkube/blob/master/jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java) were updated recently. It would be nice if you could check these behave as expected.And maybe provide your enhancement in JKube instead of here.

Also, considering the changes in your branch, WildFlySwarmGenerator could be **improved** (+renamed, +moved to separate package) to support both _deprecated_ wildfly swarm and [wildfly-jar-maven-plugin](https://github.com/wildfly-extras/wildfly-jar-maven-plugin). Both generators look very alike.

**Comment by jfdenise** [comment]
@manusa , Thank-you for sharing this information. I will open a new issue against JKube. Seems that I shouldn't carry-on with fabric8 then.

**Comment by jfdenise** [comment]
Closed, moved to JKube: https://github.com/eclipse/jkube/issues/283
