### ISSUE TITLE
remove the external loadbalancer default config from kubernetes services

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#262]
External loadbalancers are restricted to a small number on GKE and for AWS incur a cost so we should avoid creating services with this config.  

Instead now that the nginx ingress controller is working for plain kubernetes and fabric8 we ought to create ingress rules or have another microservice running that watches for new services (perhaps with a specific label) that will automatically create the ingress rule.

A quick grep through the f-m-p repo suggests there's some logic that uses the LoadBalacer metadata on services so simply removing the default config may break a few things.

**Comment by leoblanc** [comment]
Hi James, first of all, congratulations for your work on Fabric8! I have a question please and maybe it's related to this issue.

I have deployed Kubernetes 1.5 on AWS. Then, I have installed the nginx-lego Ingress Controller (https://github.com/kubernetes/charts/tree/master/stable/nginx-lego). Then, I have installed Fabric8 on top using Helm (I had some issues trying to use gofabric8 with persistent volumes on AWS, that's why I use Helm). 

I have created a Route53 CNAME record (*.default.sub.domain.com) pointing to the AWS load balancer url created for the Ingress Controller (the url shown at "kubectl describe svc nginx-nginx-lego --namespace kube-system | grep Ingress | awk '{print $3}'"). With this setup, and thanks to the exposecontrolller and the Ingress rules created by him, I can access all the Fabric8 components using their friendly DNS names. So, I can go to http://fabric8.default.sub.domain.com, http://gogs.default.sub.domain.com, http://jenkins.default.sub.domain.com etc. So far so good.

Then, I used the Fabric8 dashboard to create the application on Gogs (the Spring test microservice which shows the "Reply: Hello World!" output). The build process is successful. So, I have the following:

![environments](https://cloud.githubusercontent.com/assets/25181059/22426844/a72b68ac-e6df-11e6-8d50-2dcbbcacd7d2.png)

Ok, now this is where I have a problem: if I click the little icon to open each service in a new tab, I'm redirected to -for example- http://test.default-production.sub.domain.com. But the application is not loaded. However, I have noted on the AWS console that Fabric8 has created 3 new AWS loadbalancers for this application (one for each environment). If I navigate to the urls of these 3 AWS loadbalancers, I can see the "Reply: Hello World!" message. So, the app is working but it's available via AWS loadbalancers.

I could fix this problem creating DNS CNAME records on Route53 so test.default-production.sub.domain.com points to the url of their AWS load balancer (and it works). However, I prefer not use AWS loadbalancers. In fact, I don't understand why Fabric8 has created the AWS loadbalancers. On the configmap of the "exposecontroller" I have the following configuration:

```
domain: sub.domain.com
exposer: Ingress
```

As you can see, I'm not using "exposer: LoadBalancer" on the configmap of the exposecontroller. So, my question is: when I create an application on Fabric8 (my test Spring app), is not supposed that Fabric8 will create new Ingress rules so I don't need the use of AWS loadbalancers? Or maybe I'm confused and the exposecontroller is only used for the internal Fabric8 services (Jenkins, Gogs, Nexus, etc) but can't be used for my custom apps? (Test, etc).

Thank you very much in advance for your feedback!
