### ISSUE TITLE
kubernetes.yml doesn't include the registry prefix

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#286]
Just been updating the fabric8 docs and need to check the workflow for f-m-p...

If I generate a springboot quickstart and deploy it on a kubernetes cluster (not minikube) I add the `fabric8:push` goal which does push the image but the pod fails to start and it can't find the image, the registry prefix was never added to the kubernetes.yml

to recreate (registry is behind VPN sorry incase others want to recreate)

```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.2:generate -Dfilter=io.fabric8:spring-boot-camel-archetype -DgroupId=my.test -DartifactId=fabric8-test-project
cd fabric8-test-project
mvn clean fabric8:run  -Ddocker.push.registry=fabric8-docker-registry.default.beast.fabric8.io
```

```
kubectl get pods
fabric8-test-project-2364102176-hjgtf      0/1       ErrImagePull       0          7s
```

```
kubectl describe pod fabric8-test-project-2364102176-hjgtf 
Failed to pull image "test/fabric8-test-project:latest": Error: image test/fabric8-test-project:latest not found
```

Checking the `./target/classes/META-INF/fabric8/kubernetes.yml` shows the registry isn't added to the image name

```
        containers:
          image: "test/fabric8-test-project:latest"
```

**Comment by rawlingsj** [comment]
FWIW this means we cant run any of of new f-m-p enabled quickstarts in a cluster of more than 1 node as the kubernetes.yml is missing the registry to pull the image from.

**Comment by rhuss** [comment]
There are two possible solutions, one which already works yet, the other we need an update of f-m-p for:

* Use the same trick in the `<image><name>${fabric8.userPrefix}....</name></image>` which will be used in the resource descriptor, too. However, this feels a bit clumsy
* Use a configuration top-level POM registry-element `<registry>${custom.registry}</registry>` with a default value of `docker.io` for the `${custom.registry}`. That way everybody can override this with `mvn -Dcustom.registry=myregistry` on the command line. The registry should end up in the deployment descriptor, too (if used for kubernetes). That needs some work a new f-m-p release.

In any case we should make the user part of an image name configurable via a property so that it can be pushed to docker.io by anybody else, too.

**Comment by rawlingsj** [comment]
Ok so I think I follow, I think some work is needed to the [mavenCanaryRelease.groovy](https://github.com/fabric8io/jenkins-pipeline-library/blob/master/vars/mavenCanaryRelease.groovy#L20) and quickstarts to work with the new f-m-p, at the moment some quickstarts work and some don't for different reasons and if they use the new or old f-m-p.

e.g this is the current command we use to build the image, then we have a hack to docker tag the image after if we need to include the registry prefix.

`mvn install -U org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy io.fabric8:docker-maven-plugin:${dockerMavenPluginVersion}:build -Dfabric8.image=${user}/${env.JOB_NAME}:${config.version} -Dspring.boot.name=${env.FABRIC8_DOCKER_REGISTRY_SERVICE_HOST}:${env.FABRIC8_DOCKER_REGISTRY_SERVICE_PORT}/${user}/${env.JOB_NAME}:${config.version} -Dfabric8.dockerUser=${env.FABRIC8_DOCKER_REGISTRY_SERVICE_HOST}:${env.FABRIC8_DOCKER_REGISTRY_SERVICE_PORT}/${user}/`

**Comment by srjturner** [comment]
@rhuss Please can you expand on your first option? What would force the generated kubernetes.yml to contain the prefix of a remote registry?

**Comment by srjturner** [comment]
@rhuss Is there any way of influencing the generated kubernetes.yml file to include a registry prefix and still use a generator (rather than XML or external Dockerfile) to generate the image? It seems that as soon as I add an <image> tag I am taking on the responsibility for controlling the image generation, not just its name (and specifying just a <registry> has no effect on kubernetes.yml). Thanks.

**Comment by chicagozer** [comment]
Pretty sure I hit the same issue as @srjturner.

I changed the plugin config to point at my private Amazon ECR registry and fabric8 pushes my image with no issue.

` <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>${fabric8.maven.plugin.version}</version>
        <configuration>
  		<registry>860275329454.dkr.ecr.us-east-1.amazonaws.com</registry>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
`

However my image has no prefix in the deployment.yml, so kubernetes can't start the pod.

` image: quickstarts/spring-boot-webmvc:snapshot-161129-125348-0322`

**Comment by davidkuster** [comment]
Hi all, digging into this issue as we're having this problem with a private registry. We may fix it with a manual `sed` step in Jenkins to rewrite the image name in the generated `kubernetes.yml` deployment and insert the registry name, but would prefer to avoid that if possible.

I'm likely not far into this enough yet, but wondering if perhaps a fix is possible not from this plugin, but from the upstream Fabric8 Docker Maven plugin? Notably, if [ImageNameFormatter](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/util/ImageNameFormatter.java#L87) supported something like `%r` (for registry name) then we could specify [fabric8.generator.name](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/doc/src/main/asciidoc/inc/generator/_options_common.adoc#image-name-placeholders) as something like `%r/%g/%a:%l` and I think this plugin might not need updates.

Does that sound viable?

**Comment by rhuss** [comment]
I agree that there should be support from f-m-p for dealing with registries in the K8s resource descriptors as part of image names. 

Actually, putting it into the format pattern is a bit tricky because of the `/` separator (we could add the trailing slash as part of the %r registry placeholder, so that a pattern would like `%r%g/%a:%l` which then works also for an empty registry).

Alternatively we could also introduce a `fabric8.generator.registry` common option for the generators which adds this registry then to the generated [ImageConfiguration](https://github.com/fabric8io/docker-maven-plugin/blob/d6d2cbe0a4c8c259b04a24d63f6394d77db51bfc/src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java#L34) (thats what generator do, creating such an object)

The missing part is that the resource descriptor generation should respect the `ImageConfiguration.registry` field (and also any other globally registered registry as described in [Registry handling](https://maven.fabric8.io/#registry). I consider this is a bug if this doesn't already happen.

To summarise, I think there are these task to solve the overall issue:

* Fix the resource generation to add a registry to the image name in container spec (if the image name doesn't already include a registry as part of its name)
* Allow a `fabric8.generator.registry` property for fine grained registry setting on the generator (but the global `<registry>` setting would do it too in most cases, I guess). However this could be different as a global registry as the registry's address could look different from outside the cluster (needed for push) than from inside the cluster (maybe an internal k8s service name ?). At least one would be flexible here.
* Introducing a `%r` pattern for the replacing it with `<registry>/` when a registry is configured. But that's probably not needed if the changes above are introduced (as it does not support any additional use case ?)

@davidkuster would this cover your use case ? I.e. if a registry is used that way, the registry used for `fabric8:push` would be inserted as prefix to images added in `fabric8:resource`.

**Comment by davidkuster** [comment]
@rhuss thanks for your feedback. In terms of this possibly being a bug, the short version is that if I run `mvn fabric8:resource -Ddocker.registry=<registry>` the resulting image in the resource descriptor does not include the registry name/url. It sounds like you expect this would happen, but from doing some step debugging I'm never seeing that value get populated into the `ImageConfiguration.registry` field.

Following up on the idea of adding a `fabric8.generator.registry` property I tried manually setting a registry value on the `BuildImageConfiguration.Builder` in [BaseGenerator](https://github.com/fabric8io/fabric8-maven-plugin/blob/ad530991ef343d547ae124504aa5c138a496abcf/generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java#L115)  but that wasn't successful. I don't know if that's because [ImageConfiguration.Builder](https://github.com/fabric8io/docker-maven-plugin/blob/dffb030a2d04bdfe9a2f397e5d387d05b982918f/src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java#L159) does have explicit support for the registry field. And I see there's no setter for registry in there, but I'll see if there's some way to access it via the `@Parameter` annotation. I haven't done any Maven plugin development, so your help and patience with my flailing about is appreciated. :)

**Comment by davidkuster** [comment]
I figured out the `@Parameter` annotation, but adding this to the pom only partially had an effect:

               <configuration>
                    <images>
                        <image>
                            <name>%g/%a:%t</name>
                            <registry>my.registry.url</registry>
                        </image>
                    </images>
                </configuration>

That did populate the `ImageConfiguration.registry` field passed in the configs list to `JavaExecGenerator.customize()`, but it failed to propagate through to the [imageBuilder](https://github.com/fabric8io/fabric8-maven-plugin/blob/0f0a939b5729e529e2834bd264460595547b67b9/generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java#L126) in that class. 

I've come up with a very hacky workaround, but from some initial testing this will pick up a registry specified value specified in either the pom or on the command line and update the container image name if the registry value exists. Again, I stress the hacky nature of this, but hopefully it helps lead to a real fix. 

https://github.com/fabric8io/fabric8-maven-plugin/compare/master...davidkuster:fix/issues-286?expand=1

**Comment by rhuss** [comment]
> It sounds like you expect this would happen, but from doing some step debugging I'm never seeing that value get populated into the ImageConfiguration.registry field.

That's a well known issue ;-) Plan to fix it with this issue ...

> Following up on the idea of adding a fabric8.generator.registry property I tried manually setting a registry value on the BuildImageConfiguration.Builder ....

You are right, the registry is not yet used from the generators. The registry would be sett via the builder pattern there and then need to be evaluated in the `ImageEnricher`. When its missing in the builder we need to add this in docker-maven-plugin (was probably only forgotten), from where the code originates.

@davidkuster thanks for your investigations, I hope I can work on this issue next week. The fix shouldn't be that complicated.

**Comment by davidkuster** [comment]
@rhuss not sure if you've made any progress on this but I heard from my colleague who's doing the Jenkins side of things. He determined that "the github.com/fabric8io/fabric8-pipeline-library Jenkins library overwrites the output of the image location with the correct registry. It sees you specified a custom registry and edits the yaml before it pushes it to Kubernetes." It's possible this has masked the issue at hand for some users/envs.

Also, for some other work I have gotten around this via a `sed` step as I mentioned originally:

    $ mvn clean package fabric8:build fabric8:push -Ddocker.registry=<registry_url> -Ddocker.username=<username> -Ddocker.password=<password>      
    $ sed -i '' 's_image: <artifact>/<service>_image: <registry_url>/<artifact>/<service>_g' target/classes/META-INF/fabric8/kubernetes.yml      
    $ mvn fabric8:apply

From a scripting perspective it's not the worst thing. But, would still be a nice-to-have if this was resolved.

Thanks again for your time and attention on this!

**Comment by rhuss** [comment]
@davidkuster It's indeed a bug with I plan to address soon, probably next week (as I'm super busy this week). Feel free to ping me if there is no solution until the end of next week ;)

**Comment by bilak** [comment]
@rhuss hi, any update on this? Thanks

**Comment by rhuss** [comment]
sorry, not yet. things have piled up, working hard on my backlog ;-( Need to integrate some PRs first, but then come back to this.

**Comment by bilak** [comment]
@rhuss something new?

**Comment by boeboe** [comment]
Any update on this issues? I'm having it as well.

**Comment by rhuss** [comment]
@boeboe sorry,  no. I had to move to another project and are not actively working on fmp at the moment. But maybe @nicolaferraro or @jstrachan can help ? I think, too, that this is a very important issue to resolve.

**Comment by emichaf** [comment]
Any progress on the solution?
