### ISSUE TITLE
create a `mvn fabric8:install` command to ensure that there's a local kubectl + gofabric8 + minikube installed and that the console is running

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#299]
so it checks that 

* the binaries for gofabric8, kubectl, minikube are installed & up to date (updating them if required and the user agrees)
* ensures there's a cluster running (calling minikube start if not)
* ensures the fabric8 console is installed (installs if it not)
* shows some help on listing pods via kubectl and showing the console URL etc

**Comment by jstrachan** [comment]
@jimmidyson had a good point on IRC that we should try simplify the gofabric8 + mini* experience for all users whether they use maven or not - which I agree with too really.

Maybe we should do some of the above install goal inside gofabric8 automatically? e.g. if there's no ~/.kube/config available when we run `gofabric8 deploy` then download minikube then run minikube start etc?

Then the `mvn fabric8:install` just acts as a simple bootstrap mechanism to download gofabric8+minikube + create a cluster + install the fabric8 console

**Comment by jstrachan** [comment]
almost there, just needs the install docs on adding the fabric8 addon?
https://github.com/fabric8io/fabric8-spring/blob/master/docs/getting-started.md#intellij

Wonder if we need to separate the 'install' part from the 'create app' part so its easier to grok

**Comment by jimmidyson** [comment]
Thinking about this can we not install minikube etc to .m2 so we can use the same location for other tools if we decide to do tooling for other platforms/langs/build tools?

Also how are you thinking about handling putting the binaries into the PATH?

**Comment by jstrachan** [comment]
yeah - storing in the ~/.m2/repo sounds like a nice idea.

I guess if gofabric8 + minikube/shift is started from mvn, we don't need to put it on the PATH. Or we could have a user configurable folder to put binaries inside?

**Comment by jimmidyson** [comment]
I meant don't install to .m2 - better to have a consistent location across langs/platforms/build tools. e.g if we ever do node tooling we won't reference .m2 will we? Something like $HOME/.fabric8 would make more sense to me.

kubectl needs to be in PATH unless you're hoping to abstract that away as well?

**Comment by jstrachan** [comment]
Agreed. Lets forget the ~/.m2/repository and just use some configured folder (that we could default to ~/fabric8 unless folks provide another)? If its not on the PATH we could update the ~/.bashrc on OS X to add it in for users?

**Comment by jstrachan** [comment]
I wonder if the user has `brew` installed we should just use that to install the binaries?
```
brew install kubernetes-cli
```

**Comment by jstrachan** [comment]
mind you kubectl is kinda old in brew: "v1.2.4+3eed1e3

**Comment by rhuss** [comment]
> Agreed. Lets forget the ~/.m2/repository and just use some configured folder (that we could default to ~/fabric8 unless folks provide another)? If its not on the PATH we could update the ~/.bashrc on OS X to add it in for users?

I wouldn't do that. It makes far too many  assumptions, namely that you are using OS X and bash (e.g. I use zsh). There are also Windows users using this plugin and more. As I said, I'm really not a fan of doing this from within the plugin, i.e. adding or modifying files & data **outside** of the Maven project directory. I don't really see the benefit of installing minishift from Maven or from e.g. gofabric8 (which could be available from brew). What so different from 'mvn fabric8:install' and 'brew install gofabric8' or 'yum install gofabric8' or whatever package manager except that the later is a much, much a better fit for installing stuff (and updating and removing and managing dependencies ....). 

Please also consider the maintenance and support point of view. If we offer such a functionality, how should we possibly support all the different environments or add some sort of QA for this ? (except that it runs on our notebooks). 

As much as love self contained systems, this goes over the top IMO. You wouldn't install a Oracle DB from a mvn command, would you ? Installing Karaf with a Maven plugin is a corner case imo as Karaf is done in Java and is much more platform agnostic. And its also only easy reachable from within the project, not from the outside.

Docker, OpenShift, Kubernetes are infrastructure components which we *should not* (even if we can) abstract away (because thats not the duty of a build tool).

**Comment by jimmidyson** [comment]
@rhuss I agree with you. I guess I was feeling a bit resigned to the fact that it's happening & trying to find the least bad approach.

But if it's still up for debate, I would also be against adding this functionality, as I argued on IRC.

**Comment by rhuss** [comment]
> I meant don't install to .m2 - better to have a consistent location across langs/platforms/build tools. e.g if we ever do node tooling we won't reference .m2 will we? Something like $HOME/.fabric8 would make more sense to me.

@jimmidyson I don't think we would use 'mvn fabric8:install' for doing a node build and don't want to couple the node tooling (npm) to the conventions used by a Maven plugin. I really would love to have a single tool for managing the infra, and that's not Maven.

Another example: For d-m-p we use docker-machine to set up a Docker daemon if not existing. docker-machine must be installed though. But all the management is then done by docker-machine, which is the 'infrastructure installer' (and has other deps like virtual box or so).

If gofabric8 could be such a tool for Kubernetes / OpenShift and the plugin only delegates to it with single commands like 'install', 'update' and 'remove' this would be perfect. However, gofabric8 should still be installed by the user (as docker-machine has to be done).

**Comment by jimmidyson** [comment]
What I meant was if we set a precedent with mvn fabric8:install & then decided to do something similar with node tooling then locations should be consistent.

:+1: for making gofabric8 the provisioning tool for local dev.

**Comment by jstrachan** [comment]
If folks had brew then something like this would be good:

    $ brew install fabric8
    gofabric8, kubectl & minikube now installed

     $ gofabric8 start

The main Issue is not everyone uses brew or has an up to date brew install.  I guess we could have a bash script for non brew folks - but then bash scripts don't work on most Windows boxes - hence using mvn as a simple bootstrap for non-brew users?

**Comment by rhuss** [comment]
Your are absolutely right, Maven (or Java) give you some cross-platform executability, but when installing things into the OS this uniformity is almost gone. There are so many things which differ on different platforms (even on different distro of the same OS):

* Different pathes for binaries
* Different ways to setup a path
* Interference with such tools already installed
* Global installations require root (which would need to be documented).
* File permissions are different
* ....

That's all stuff installers like [IzPack](http://izpack.org/) or [InstallAnywhere](http://www.flexerasoftware.com/producer/products/software-installation/installanywhere/) (which I used and cursed a lot in my former life) are for.

What's about the following (alternative) ideas:

* Package kubectl and minikube within gofabric8 (much like OpenShift does for its contained binaries) and extract it on 'gofabric8 install'. Or have a new 'fabric8-installer' with kubectl, minikube and gofabric8 contained. Or downloaded on 'gofabric8 install'.
* Provide an installer something like Docker-toolbox (much work, though).

gofabric8 would be uniformly accessible on all platforms (since its a go binary) and could do the installation as well. In that sense its similar to Maven (all you need is this binary which you simply can download) that it run on all platforms the same way.

**Comment by jstrachan** [comment]
So we're all agreed that either folks should install the binaries via brew; or that gofabric8 should install minikube + kubectl somewhere on the PATH and do any necessary modifications of PATH.

I'm just suggesting that a mvn goal could automate the downloading and running of gofabric8 - thats it. Then we leave all the operating system stuff (PATH / downloading binaries) to gofabric8 - apart from downloading the gofabric8 binary itself. gofabric8 can then decide if it wishes to copy its own binary to where it put minikube + kubectl

**Comment by jstrachan** [comment]
i.e. gofabric8 does almost all the work:
https://github.com/fabric8io/gofabric8/issues/108

we just provide a little bit of java sugar around downloading and running gofabric8

**Comment by rawlingsj** [comment]
I like this, for anyone that doesn't know gofabric8 but knows how to add a maven pom dependency then I think this is another "make it as easy as possible to get going" approach.   Having gofabric8 do all the work makes total sense and is the right polyglot solution, but as we already have maven tooling designed to make it easy for java folks to work with kubernetes, a maven goal that helps with the initial downloads makes sense to me.  

Of course our recommend approach is still to use gofabric8 but to tempt a java dev that knows nothing of docker, kubernetes, gofabric8 etc but does want to try out their java code / app in a cloud environment and then learn more, this sounds great.  

If it does help adoption with java devs then we can look at doing the same for other tooling like yoeman etc but it's worth finding out first.

**Comment by jstrachan** [comment]
Agreed. Plus the [mvn fabric8:setup goal](https://github.com/jstrachan/fabric8-maven-plugin/blob/ce556de3321c4ef681fa96d7e106230a0ff7b4bb/doc/src/main/asciidoc/inc/_fabric8-setup.adoc) adds the mvn plugin to the pom.xml too; so after running that users can type `mvn fabric8:install` (to download + run gofabric8 install) or whatever we call the goals/commands

**Comment by rhuss** [comment]
@jstrachan @rawlingsj I'm really perfectly fine to delegate to `gofabric8` for installing and managing stuff. I just don't want f-m-p to do installation tasks itself (like modifying .bashrc for setting pathes or downloading kubectl / minishift ...) in order to make the scope clear and having a single installer also usable outside of Maven.

Its a little bit similar how d-m-p delegates to Docker Machine as described [here](https://dmp.fabric8.io/#docker-machine)

**Comment by jstrachan** [comment]
@rhuss agreed. I think delegating to gofabric8 is a good balance; lets folks get started quickly without having to install brew or download stuff and mess with the PATH etc - while leaving the `mvn fabric8:install` goal super simple (download a binary for the right platform into ~/.m2/repository somewhere and run it)

**Comment by jstrachan** [comment]
think we can close this one now
