### ISSUE TITLE
naming of deploy / run / run-interactive goals

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#364]
so I'm liking the `fabric8:run-interactive` behaviour (run and tail the log until Ctrl-C) be called `fabric8:run` as its then very much like existing goals developers are aware of (`spring-boot:run`, `tomcat:run`, `jetty:run`, `wildfly:run` etc). Seeing things start and the log is really really handy!

We already have `fabric8:deploy` / `fabric8:undeploy` to deploy/undeploy. I wonder if we just remove the current `fabric8:run` goal completely? 

i.e. do we need a 'run in background' or 'deploy' goal that forces the Install goal to be run? 

I wonder if these 2 options are enough:

```
mvn install fabric8:deploy
mvn fabric8:run
```

Or maybe we need some goal name for 'install and deploy'; not totally sure what to call it though ;) 

Maybe we rename the old mvn fabric8:deploy goal to be something more implementation specific; mvn fabric8:apply - then use `fabric8:deploy` to be invoke install and apply goals?

So folks could do either of these to deploy resources:
```
mvn install fabric8:apply
mvn fabric8:deploy
```
or to run interactively its
```
mvn fabric8:run
```

Then folks either use deploy/undeploy (which matches to other app server like goals) - then run is considered special (as its a deploy, tail log and undeploy on Ctrl-C combined into a single goal). Then things feel more app-server like?

**Comment by rhuss** [comment]
I'm also for removing the current `fabric8:run` as it does not add much over `fabric8:deploy`. The same effect can be achieved by binding `fabric8:deploy` as execution phase so that a `mvn install` deploys these, too (but thats of course a matter of taste).

I wouldn't introduce both 'fabric8:deploy' and 'fabric8:apply' for doing difference things since they can be easily confused (i even dont grok the difference yet ;-)

Another solution could be to adopt the Docker semantics: Adding a parameter '-Dfabric8.interactive' (similar to '-i' for `docker run`). 

Tomcat uses `start` and `run` to differentiate these two case. 

While we are at naming: What about renaming 'cluster-start' and 'cluster-stop' to 'up' and 'down' (analog to 'ifconfig up') ? 

Then we have still 'start' and 'stop' free to use e.g. for 'deploy' and 'undeploy'. Then we would exactly have the Tomcat semantics ('start' & 'stop' for background tasks, 'run' for foreground task).

Maybe we could leave 'deploy' still as an alias for 'start' then.

**Comment by jstrachan** [comment]
So I like the idea of folks being able to type `mvn fabric8:deploy` and things work (so triggering the `mvn install` goal before it).  

Then we just need to decide if we need 2 flavours of this goal - one that does fork 'install' first and one that doesn't. Personally I have found it handy once I've built an image to just invoke 'mvn fabric8:resource fabric8:deploy goals' - i.e. skip building java code, running unit tests + doing a docker build (which can be slow) - and just generate + reapply the manifests. e.g. if you do a build and the deploy fails due to some manifest issue; its nice to just rerun the resource generation + apply parts. Maybe for this advanced/internal goal we name it something more literal; how about `mvn fabric8:apply-resources`?

For the tomcat `start` versus `run`; it looks like tomcat has `start`/`stop` (which starts and stops a deployed app) and `deploy`/`undeploy` then `run`. Maybe we should do the same?

So `start` would scale the D/DC/RC/RS up to 1 and `stop` would scale it down again? (So its the less drastic version of `delete`?

On the `cluster-start` -> `up` - I kinda like start/stop for clusters as thats the commands that gofabric8, minikube, minishift use. Starting/stopping a cluster is more rare; but they feel like the right names so am still preferring `cluster-start` and `cluster-stop` really

**Comment by jstrachan** [comment]
here's the current proposed docs for the goals:

* fabric8:apply https://github.com/jstrachan/fabric8-maven-plugin/blob/4382515150a7047192b4296d01833e9663fb37ee/doc/src/main/asciidoc/inc/_fabric8-apply.adoc
* fabric8:deploy https://github.com/jstrachan/fabric8-maven-plugin/blob/4382515150a7047192b4296d01833e9663fb37ee/doc/src/main/asciidoc/inc/_fabric8-deploy.adoc
* fabric8:run https://github.com/jstrachan/fabric8-maven-plugin/blob/4382515150a7047192b4296d01833e9663fb37ee/doc/src/main/asciidoc/inc/_fabric8-run.adoc

the end of the `fabric8:apply` goals justify why it needs to exist really. Maybe we rename it be a bit longer and more specific like `fabric8:apply-resources` though?

**Comment by rhuss** [comment]
To summarize, you suggest the following changes:

* fabric8:deploy --> fabric8:apply
* fabric8:run --> fabric8:deploy
* fabric8:run-interactive --> fabric8:run

As said imo **apply** and **deploy** are to close to each other w.r.t to meaning so the might get confused. But thats my opinion as a non-native speaker. would love to hear other opinions here, too.
Maybe something like `fabric8:all`, `fabric8:build-apply`, `fabric8:full` could do it, too (for specifying a full build circle) ?

**Comment by rhuss** [comment]
Aggreed btw for start / stop instead of up / down (wonder though whether minishift could be called a "cluster").

I know, I'm playing the nit-picker here, but I found naming incredible hard and incredible important for a good UX. Especially goals and their names should be:

* short (a single word at best without hypens)
* consistent (e.g. start / stop not run / stop) 
* having  'good' associations
* similar to well known concepts (principle of least surprise)
* unambiguous
* no much overlap

Don't mind much when I'm not getting my suggestions through (which of course is also partly a matter of taste), I just want that we do not take the decisions lightly.

**Comment by jstrachan** [comment]
gonna close this for now - lets reopen with new naming issues as we think of things we don't like so much etc
