### ISSUE TITLE
Image sha256:xxx does not contain a value for the io.openshift.s2i.scripts-url label

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#397]
When I run this script 

```
#!/bin/bash

echo "## Start minishift if not yet done"
./bin/start_minishift.sh

echo "## Start minishift if not yet done"
./bin/clean-project.sh

echo "## Create the configMap"
oc create configmap app-config --from-file=src/main/resources/app.json

echo "## Remove old docker image"
docker rmi -f vertx-demo/simple-config-map:1.0.0-SNAPSHOT

echo "## Create the docker image, kubernetes/openshift config file and deploy the pod"
mvn clean fabric8:run -Dfabric8.mode=openshift
```

to deploy this project (https://github.com/redhat-microservices/quick_vertx_kube-configmap/tree/migrate-to-new-f8-plugin)

The pod created contains this error (oc logs pod)

```
Image sha256:0d935f4b122ad022125424bb64fdd10a7b624203839b1344317740af9ec20760 does not contain a value for the io.openshift.s2i.scripts-url label
```

To test:

```
git clone git@github.com:redhat-microservices/quick_vertx_kube-configmap.git
cd quick_vertx_kube-configmap
git checkout migrate-to-new-f8-plugin
// Start minishift
bin/deploy_openshiftmode_test.sh 
```

**Comment by rhuss** [comment]
As I tried to explain in other issues, too, if you use an **openshift** build with a **s2i* strategy, then your base image given with `<from>` must be a s2i builder image confirming to the s2i rules. The generators which automatically build your image configuration take care of this. If you provide your the comage configuration as you [do in your example](https://github.com/redhat-microservices/quick_vertx_kube-configmap/blob/migrate-to-new-f8-plugin/pom.xml#L151), then you must take care yourself.

As an alternative you can use a **docker** strategy for an openshift build which works more or less like a plain docker build.

Confessedly the documentation at https://maven.fabric8.io is not yet complete. But this build aspec is explained quite toroughly in https://maven.fabric8.io/#fabric8:build . In order to improve here, it would be awesome what is not so understandable in this section so that we can fix that. Seems I couldn't explain it well enough.

**Comment by cmoulliard** [comment]
Do we have s2i builder image that we can reuse for such project/demo ? Where can we find info about s2i rules ?

**Comment by rhuss** [comment]
In the openshift documentation you find a lot of information about s2i. Our community s2i images are `fabric8/s2i-java` (github: https://github.com/fabric8io-images/s2i) and the FIS product s2i images are `jboss-fuse-6/fis-java-openshift`

**Comment by rhuss** [comment]
Generators use `fabric8/s2i-java:2.1.0` as base image.

**Comment by rhuss** [comment]
'hope its ok to close this issue (we just in a big sweep-cleanup phase). If not, please reopen.
