### ISSUE TITLE
sourceStrategy.from.name: Invalid value: "fabric8/s2i-java"

### ISSUE THREAD

**Issue by chirino** [fabric8io/fabric8-maven-plugin#430]
Seems fabric8/s2i-java is not a valid image stream name.  When run against OpenShift, the following:
    
    git clone git://github.com/fabric8-quickstarts/spring-boot-camel.git 
    cd spring-boot-camel
    mvn clean install -Dfabric8.build.recreate=all fabric8:deploy  -Dfabric8.mode=auto

fails with:

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.53:build (default) on project spring-boot-camel: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.53:build failed: Failure executing: POST at: https://192.168.64.2:8443/oapi/v1/namespaces/test/buildconfigs. Message: BuildConfig "spring-boot-camel" is invalid: spec.strategy.sourceStrategy.from.name: Invalid value: "fabric8/s2i-java": ImageStreamTag name contains invalid syntax. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.strategy.sourceStrategy.from.name, message=Invalid value: "fabric8/s2i-java": ImageStreamTag name contains invalid syntax, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=BuildConfig, name=spring-boot-camel, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=BuildConfig "spring-boot-camel" is invalid: spec.strategy.sourceStrategy.from.name: Invalid value: "fabric8/s2i-java": ImageStreamTag name contains invalid syntax, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}). -> [Help 1]

**Comment by rhuss** [comment]
Previously, the from was always considered to be a Docker image name, for which fabric8/s2i-java is perfectly valid.

However when you change this to an `ImageStream`, it must be a [simple name](https://github.com/openshift/origin/blob/48f6a2807d7b2920b5301152cbe2e8168bb7d4bf/pkg/image/api/validation/validation.go#L37) without [registry part](https://github.com/openshift/origin/blob/48f6a2807d7b2920b5301152cbe2e8168bb7d4bf/pkg/api/helpers.go#L13).

An image stream can not have an obvious default value since it depends on your installation. So the only I way I currently see to use an `ImageStream` or `ImageStreamTag` as base image to provide it with the configuration: Either `-Dfabric8.generator.from` or within a `<generator><config><spring-boot>` config section.

**Comment by jstrachan** [comment]
I've a possible fix for this issue in the PR; we should continue to default to DockerImage as its going to be the most common approach; reusing docker images from public docker registries as opposed to creating image streams for the actual builders

**Comment by jstrachan** [comment]
this is now fixed; the default docker images are all used as `DockerImage` unless the user configures an ImageStream or one day we move to an approach of auto-creating an ImageStream on the fly; though don't see much real use for that any time soon (its better to put the base image in your pom.xml for git versioning)

**Comment by rhuss** [comment]
fwiw we could still put the docker image name in the pom.xml but create an `ImageStream` for this specific image, so versioning is probably not so much an issue.
