### ISSUE TITLE
gofabric8 version check

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/fabric8-maven-plugin#483]
As discussed in #482, the current method of doing the version check is fragile & a borked gofabric8 release (as happened today) means that everyone's `mvn fabric8:cluster-start` stops working too. The problem is that the current way to check for the latest version is to read `https://raw.githubusercontent.com/fabric8io/gofabric8/master/version/VERSION`. That file is on a development branch (master) & indicates the current dev version, not latest released version.

We need to change to a different method for checking for updated versions. In [minishift](https://github.com/fabric8io/minishift), we use github releases API. This works great, but due to rate limiting on unauthenticated requests sometimes causes updates to fail. A simple oauth token to add to requests can get around that, but you might consider that too much.

**Comment by rhuss** [comment]
My suggestion is to use a property in `pom.xml` for the current stable gofabric8 version. This property then can be updated for each gofabric8 version by our CD as we do for other properties, too.

If there are no objections I'll change this and put it into a `<version.gofabric8>` property in the parent pom.xml

**Comment by jimmidyson** [comment]
So you're suggesting a new release every time there's a gofabric8 release? I'm personally not too keen on that as I can see there being times when the plugin isn't in a state to be released & a new version of gofabric8 is ready to be consumed.

**Comment by rhuss** [comment]
I mean that an application should declare its dependencies clearly. So when f-m-p depends on gofabric8 it should declare the version it depends on (because, considering we would have tests, this is the version we tested against). The situation we just has was, that a "new" version of gofabric8 (i.e. something changed on the gofabric8 side) broke fabric8-maven-plugin. I know this could be hardened by using real releases from the GitHub API, but it still leaves open the question, whether an application should be defensive by defining its dependencies or trust every new shiny release of gofabric8.

If we consider to always use the newest release, why don't we use always SNAPSHOT for all our projects and depend on them ?

It's really depends on your point of view. I'm about to send a PR for doing it 'conservatively' since I'm a fan of stating dependencies explicitly, but it depends on the discussions here, whether we want it to apply. BTW, all our other dependencies e.g. on fabric8 or kubernetes0client itself works by providing explicit versions in the pom.xml

If there is a new release of gofabric8 which is required by f-m-p for some fix or new features, I would release a new version of f-m-p.

**Comment by rohanKanojia** [comment]
Since gofabric8 is not supported anymore, not sure if this issue is still valid. Closing this, please reopen if it still looks valid to you
