### ISSUE TITLE
provide a goal to watch spring boot containers for local development changes & reload on the fly

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#503]

**Comment by rhuss** [comment]
"I think we should move now the spring-boot-generator to fabric8-maven-core, too. makes more sense as the core is now prominently coupled to spring-boot anyway. So we can avoid this unnecessary abstraction."

sorry, not my day.

This feature definitely goes absolutly in the right direction for providing an awesome developer experience. And we should have this. But not hardcoded as a goal sticking to a specific technology. This carries all this generator / enricher separation ad absurdum. I wouldn't mind if we open a spring-boot-kubernetes-plugin which is only about spring-boot, but for a general purpose plugin this is far too specific for a goal. 

Do we plan to introduce 'fabric8:watch-widlfly-swarm', 'fabric8:watch-tomcat', ... so that each developer needs to remember whether its current microservice project (out of thousand others) is running spring-boot, widlfy-swarm, ... ?

My suggestion is to do this under the umbrella `fabric8:watch`, with maybe a first hard coded detection. Later then something like 'enricher' and 'generator', like 'watcher' which are then specific to each tech.

Isn't it all about developer experience ? why should a developer need to specify `watch-spring-boot` when the plugin could detect it itself ?

**Comment by jstrachan** [comment]
yeah - it'd be nice to just have a `fabric8:watch` and it figure out the right thing to do!

for app server like stuff like tomcat/jetty/wildfly/karaf we should be able to just reuse the current `fabric8:watch` goal really; so I'm not expecting a load of new commands.

**Comment by jstrachan** [comment]
all fixed now - see https://maven.fabric8.io/#fabric8:watch-spring-boot
