### ISSUE TITLE
can we remove the lgmt command from this repo

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#537]
can we either
- remove the lgtm dependency from this repo as discussed in https://github.com/fabric8io/fabric8-maven-plugin/pull/474
- update other fabric8 projects + cd pipelines to use lgtm
- update the pipelines to always comment lgtm + merge regardless of whether each repo needs it

Just raising this issue so that it's agreed and actioned as the f-m-p pipeline still becomes stuck every release.

The pipeline will only continue when all the PR checks pass using the github api, which still reports https://github.com/fabric8io/fabric8-maven-plugin/pull/535 as pending because it was missing the lgtm.

Anyways I hope thats a non issue and as mentioned before lgtm is removed and an effort of work is prioritised to update all fabric8 projects, workflows and pipelines to what ever the agreed approach may be?

Either that or I update the pipeline to start adding a "lgtm" comment as well as "merge" during the CI version updates but that sounds a bit excessive? 

For now I'm just looking for stability in our release pipelines and that comes with consistency across our projects as they all follow the same release pattern.

What do we think?

**Comment by rhuss** [comment]
In our current workflow the `lgtm` is not really useful since it doesn't really pushes us to more reviews.

It would make sense if:

* Somebody else than the author has to post a "lgtm"
* or: More than one has to post a "lgtm"

In the current state it doesn't make much sense, so I wouldn't mind to remove it now.

However, for a mid-term goal I still would like to enforce reviews a bit more. It would be cool if we could distinguish between the CD workflow and the regular development workflow. The easiest way IMO would be to introduce a dedicated CD user, which performs CD related Git actions. The hooks then could differentiate on the user and give the CD user more power e.g. by not doing reviews. As a nice side effect, it would be easier to filter CD releated mail notifications (which are massive).

**Comment by jimmidyson** [comment]
We should definitely remove lgtm status check, especially now that github supports code review approval, requesting changes, etc.

I'd like our flow to require a code review approval before merge but that would require updates to CD pipeline to do so.

**Comment by rhuss** [comment]
Remove **lgtm** as required check. wonder though how we could enhance a review process ?
