### ISSUE TITLE
WildFlySwarm - The generator should detect .war package

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#720]
A wildfly swarm app may be packed as a .war also. Although I guess fat jar is recommended/better.

But this example was using .war
https://github.com/davsclaus/fabric8-hello/blob/master/helloswarm/pom.xml#L8

And then it was the default .war generator that was kicked in and wanted to run it as a tomcat.

We should detect that wildfly-swarm plugin is in the pom
https://github.com/davsclaus/fabric8-hello/blob/master/helloswarm/pom.xml#L35

And let the wildfly-swarm generator kick in instead.

**Comment by jamesnetherton** [comment]
Sounds like a regression of #526.

**Comment by rhuss** [comment]
The wildfly generator is always taking over when being before the war-generator which is the case in the latest f-m-p releases already (3.2.27) (so #858 is not necessary and I will revert it if this is ok for @jstrachan )

There is still the issue that a `.war` is not picked up by the generator as the wildfly-swarm generator only deals with the fat jar. Since the fat-jar is created along side the war:

```
 ls -l target
total 273304
drwxr-xr-x  4 roland  wheel        136 Mar  6 08:42 classes
drwxr-xr-x  4 roland  wheel        136 Mar  6 08:42 docker
drwxr-xr-x  5 roland  wheel        170 Mar  6 08:42 fabric8
drwxr-xr-x  3 roland  wheel        102 Mar  6 08:42 generated-sources
drwxr-xr-x  4 roland  wheel        136 Mar  6 08:42 helloswarm
-rw-r--r--  1 roland  wheel        929 Mar  6 08:42 helloswarm-1.0-SNAPSHOT-helm.tar.gz
-rw-r--r--  1 roland  wheel  108056532 Mar  6 08:42 helloswarm-swarm.jar
-rw-r--r--  1 roland  wheel      11167 Mar  6 08:42 helloswarm.war
-rw-r--r--  1 roland  wheel   31854677 Mar  6 08:42 helloswarm.war.original
drwxr-xr-x  3 roland  wheel        102 Mar  6 08:42 maven-archiver
drwxr-xr-x  3 roland  wheel        102 Mar  6 08:42 maven-status
```

this still works, but picks up the fat jar, not the war.

The wildfly-swarm generator should be changed to detect the packaging, and if `war` is selected it should:

* Choose a different base image (e.g. a Wildfly base image)
* Pick the `.war` and not the `-swarm.jar` to put into the container.

This can be easily done for the plain Kubernetes mode, but not yet for the S2I mode as we don't have yet support for S2I webapps (but we should do this soon and this shouldn't be hard anyway).

**Comment by jstrachan** [comment]
@rhuss happy for my previous patch to be reverted.

BTW if the project creates a foo-warm.jar from the war, why not stick with the fat jar approach? Then we don't need to wait for S2I mode to support webapps?

We can let folks configure whether or not they want to use the `foo` war or the `foo-swarm` fat jar via the `<build><finalName>` configuration in the pom.xml?

e.g. this project worked great with no custom configuration of fmp (if you use my previous patch or you disable the webapp generator) since its `finalName` refers to the swarm fat jar so the fat jar approach works great
https://github.com/fabric8io/generator-backend/blob/master/pom.xml#L84

**Comment by rhuss** [comment]
For me its still works even without the #858 patch as indeed the webapp generator never kicks in if the wildfly-swarm generator is before it in the chain. This is true in the latest releases and I verified, that a usable image is created, however with the fat jar instead of the war.

A reason for people to prefer a war is, that the image to create is much smaller as the Java EE server is already included in the base image. IMO it's a deficit of the wildfly-swarm plugin that it creates the fat jar, too when a war is requested, as it might take quite some time to generate 60MB+ jar files which are no needed.

So, for the moment and with version 3.2.28 @davsclaus example works out of the box even with packaging `war` (although the fat jar is picked up).

@jstrachan if the latest version 3.2.28 without your patch doesn't work for you, it would be awesome if you could please post the log of a Maven run with -Dfabric8.verbose as we then hopefully can see why the war-generator kicks in (which it doesn't in my tests).

**Comment by rhuss** [comment]
Ok, just saw https://issues.jboss.org/browse/OBST-121 which is about the OpenShift S2I build. Let me check that, too (as I only checked the K8s case).

**Comment by davsclaus** [comment]
There is some details about WAR vs JAR here for swarm
http://wildfly-swarm.io/posts/to-war-or-jar/

**Comment by rhuss** [comment]
@jstrachan in fact https://issues.jboss.org/browse/OBST-121 is due because of a different issue: The configuration in https://github.com/gytis/rest_wildfly-swarm/blob/fmp-3.2.28/pom.xml#L144-L150 cause the wildfly-swarm generator to be put last (this shouldn't be the case of course). If you remove this, it works with the latest versions of 3.2.28 already.

I will raise a new issue for the config regression.

**Comment by jstrachan** [comment]
@rhuss ah - maybe its the `include` of the wildfly-swarm generator that actually breaks the wildfly-swarm generator (as it moves it to the end of the list) ;)

**Comment by rhuss** [comment]
@davsclaus thanks for the heads up. So, as it looks like that Wildfly Swarm recommends a `war` deployment for 'classical', REST-style Microservices instead of a fat jar. So I guess we should support this with a war base image, too (and we need to fix this asap, too. its on my list for this week ;-)

However, I still consider the creation of an additional fat-jar even when using `war` packaging a regression.
