### ISSUE TITLE
incorrectly generating an initcontainer annotation to chmod all volume mounts not just PV

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#772]
### Description
f-m-p is generating yaml to chmod 777 all volume mounts and not just the persistent volume folders that are attached to PVCs.  This means that the [Jenkins](http://central.maven.org/maven2/io/fabric8/devops/apps/jenkins/2.2.305/jenkins-2.2.305-kubernetes.yml) pod in recent releases now tries to `chmod 777 /var/run/docker.sock` in its initcontainer.  We should only chmod volumes that are attached by a persistent volume claim.

f-m-p version : 3.2.13

One more point was from memory I thought we were only adding the initcontainer annotation when generating the kubernetes.yml and not openshift.yml too.  After looking at previous commits I think this https://github.com/fabric8io/fabric8-maven-plugin/commit/90133203f2aa8e60d9c04afff75d555ed84f76c4 is related.

/cc @rhuss

**Comment by rhuss** [comment]
Agreed. The reason why its now also include in openshift.yml is, that our current model is to create a single list of resource by enrichers and filter out later in the ResourceMojo (which then, for specific cases , needs to have knowledge about certain enrichers, which of course must not be the case). 

A solution to this dilemma is proposed in #678 which would make this much clearer and introduce a better decoupling and encapsulation. Mostly its about to call enrichers twice, ones for the kubernetes.yml and once for the openshift.yml, so that the after-the-fact filter step can be avoided.

I have to run now, but will review your PR later today or tomorrow.

**Comment by rawlingsj** [comment]
This has now been released.
