### ISSUE TITLE
VolumePermissionEnricher should only generate initcontainer annotations for Kubernetes resources

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#790]
The f-m-p VolumePermissionEnricher enriches openshift resources which it didn't used to do.  This has a knock on affect and can cause problems when deploying apps on openshift. See https://github.com/fabric8io/elasticsearch-cloud-kubernetes/pull/69#issuecomment-275744474

We should update f-m-p to not add the chmod init container for openshift resources and leave it to just kubernetes resources.  

I can have a crack at this unless @rhuss you have a good idea of where the change needs to happen?

**Comment by rhuss** [comment]
The problem is that we currently create kubernetes objects first and convert to OpenShift afterwards. The enrichers are hence agnostic to the platform for these objects and can't distinguish between OpenShift and Kubernetes. That is one of the main reasons why I raised #678 , so that we have a two pass run through the enrichers, one for Kubernetes and one for OpenShift which would make things much cleaner and more decoupled (and one would get rid about this complex and error prone post-processing step in the Mojos for detangling k8s and openshift objects again from this single list).

For the current setup the only solution would be remove the init container in the Mojo as a post-processing step (which completely defeats the abstraction, decoupling, flexibility and separation-of-concerns that generators and enrichers introduce as it happens also even when the `VolumePermissionEnricher` is not enabled and would apply to every init-container).

Thats probably the only solution for now, to remove all init-containers for OpenShift objects in post-processing :(

@rawlingsj if you feel fancy, feel free to add this kind of filtering to this [method](https://github.com/rhuss/fabric8-maven-plugin/blob/d8d1d28918f82d685af05e3c62789f6d9f846ed9/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java#L475-L475)

**Comment by rawlingsj** [comment]
Ok I see - thanks @rhuss.  I've only got a couple of hours this evening and quite a few things I need to get done for next week so I'll hopefully I'll have time to have a go and do some testing.  Cheers.

**Comment by jimmidyson** [comment]
I don't think this is always required on kubernetes either, it depends on the PV provisioner.

**Comment by rhuss** [comment]
@jimmidyson is it true that OpenShift does not support init containers at all ? If so I wouldn't feel so bad to remove them always from the OpenShift resource list ;-)

@rawlingsj I will take care of this.

**Comment by jimmidyson** [comment]
Init containers are most definitely supported on openshift.

**Comment by rawlingsj** [comment]
OK many thanks @rhuss I appreciate it.  We're reliant on elasticsearch starting on openshift which was where I noticed the problem.  I think with this change it will resolve it and the next fabric8 online distro release will all start correctly - fingers crossed :)

**Comment by rhuss** [comment]
@jimmidyson ok, will find a different solution then to remove only the init container added by this specific enricher. It will not be nice and kittens will die.

**Comment by rawlingsj** [comment]
I'm still seeing the init containers being added to the openshift.yml files.  Not sure if this is a regression of the related PR or if it wasn't resolved, but building fabric8-devops even with a f-m-p snapshot still includes the init container annotations.  

fabric8-devops/elasticsearch/target/classes/META-INF/fabric8/openshift.yml still includes 
```
pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/usr/share/elasticsearch/data"],"volumeMounts":[{"mountPath":"/usr/share/elasticsearch/data","name":"data"}]}]'```

**Comment by rhuss** [comment]
Does it run in OpenShift mode (i.e. either against an OpenShift cluster or with `-Dfabric8.mode=openshift` ?) Only then the init-containers are removed from openshift.yml.

**Comment by rawlingsj** [comment]
No the CD infra is running on Google Container Engine.  For each application we generate two yaml files openshift.yml and kubernetes.yml, when we release fabric8-devops only the generated kubernetes.yml files should include the init container annotations.

**Comment by rhuss** [comment]
I mentioned this issue [several times](https://github.com/fabric8io/fabric8-maven-plugin/issues/790#issuecomment-275752809), the problem is that the enricher doesn't know for which file its adds resources.

* The solution to *always* add this init-containers hardcoded in the plugin defeats the purpose of enrichers completely and I have been already asked by other plugin users how this specific volume enrichment can be disabled (which is possible because its part of an _enricher_ and you can easily create profiles on your own).
* The solution to *always* remove init-containers hardcoded outside of enrichers again couples the main plugin to this very specific functionality not needed by everyone (also: Should every init-contaienr removed for openshift ? Only init-containers with a special name ? which name ?)

I know its a dilemma, I sketched the solution in #678, got not yet any feedback on this though,  but we (@nicolaferraro  and myself) are working on this nevertheless (but it's a big change thats why we are still careful otherwise we will break even more stuff). We want to add more integration test first (like that things like in #835 doesnt not occur anymore and are captured in a integration test).

I will find a (temporary) solution for this very problem which bugs us for so long. Sorry for the inconvenience, but maybe you understand also the forces which drives me (== covering uses cases outside of fabric8 CD) as I understand your use case (and that you are very likely highly upset because of fix for the K8s platform not working again as it has been worked before. Sorry for that, thats not my intention!).

**Comment by rawlingsj** [comment]
Its ok @rhuss I understand and I know it's not intentional :)  A temporary solution would be great as that means we'll be able to deploy fabric8-online to our openshift dedicated clusters without modifying the deployment yamls by hand.  

BTW I could probably come up with an integration test that builds one of the fabric8-devops apps, maybe Jenkins and have that build and deployed using a snapshot on every PR to f-m-p.  Whilst it's not a full pipeline test using a quickstart it would give early feedback of issues like this one and https://github.com/fabric8io/fabric8-maven-plugin/issues/835.  I can try and take a quick look this week if you'd like.

**Comment by rhuss** [comment]
@rawlingsj w.r.t to integration test, for the pure creation of resource yamls we already have setup a build at https://github.com/fabric8io/fabric8-maven-plugin/tree/master/it/src/it which allows to flexibly compare generated resource descriptors agains generated one (like [here](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/it/src/it/spring-boot/expected/kubernetes.yml#L52))

So I can easily add the one generated with an older, working version as expected input. The idea is to add such a test for every error we encounter (like the one in #835)
