### ISSUE TITLE
Introduce new "Watcher" abstraction to replace `fabric8:watch-spring-boot`

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#799]
Currently there is a top leve goal `fabric8:watch-spring-boot` which directly connects spring-boot as a technology to the the abstract goal. We already have `fabric8:watch` so the user would need to _know_ in advance what tech is used. 

This is (a) in contrast to the Maven philosophy and (b) is too much of coupling (and its too much to type). E.g. should we introduce goals like 'watch-vertx', 'watch-wildfly-swarm' then later ? 

This issue does **not** question the awesome functionality that `watch-spring-boot`  brings on the table. The goal should be to hide this functionality behind `fabric8:watch` and automatically selected by the plugin when it detects that its about s spring-boot app.

Therefore I suggest to introduce the new concept of a `Watcher` (on the same footprint as `Enricher` or `Generator`) which abstracts a way the concrete implementation _how_ to watch. This is flexible, easier to use from an UX perspective and open for additional watching features).

**Comment by nicolaferraro** [comment]
@rhuss I start working on this.

**Comment by rhuss** [comment]
Awesome, thanks ! I added you as collaborator to the project, so that you can close / change / assign stuff, too.

**Comment by nicolaferraro** [comment]
@rhuss I've looked at the current implementation of `watch` and `watch-spring-boot` and started doing some refactoring (and still fixing bugs on `watch-spring-boot`). For my understanding, what's currently implemented in `watch` will be the default watcher, while the spring-boot one will be fired under certain conditions (almost like the generators). And we'll inject other watchers the same way later.

Refactoring means for me starting to pull stuff out of mojos and define a single generic watch mojo that delegates to some service. But the `f8:watch` mojo is tightly coupled with the `docker:watch` mojo. So should we change the 'd-m-p' first? Otherwise we are going to build a (temporary?) chain of delegating mojos. wdyt?

**Comment by rhuss** [comment]
Yes we should do it for d-m-p, too, so that we can avoid the inheritance chain of Mojos (by trying to access the watch functionality directly in a backend class). Also, I wonder now how this works with OpenShift S2I as the build mechanism is different, so triggering the build works differently.

**Comment by nicolaferraro** [comment]
Yeah, I don't think the Docker watch can work for Openshift. But this is in line with our target of separating the Kubernetes/Openshift workflow.

That watcher will be set as "not applicable" when the platform mode is `openshift` and we will have a specific Openshift Watcher default implementation that will be based on.. `oc rsync`?

**Comment by rhuss** [comment]
Agreed. 

If haven't scratched my head enough for how to implement watch with OpenShift. Maybe just triggering a new build would make it, too ? (for a sledge hammer approach). But agreed, `oc rsync` support would be awesome, too.
