### ISSUE TITLE
Remove dependencies among Mojos

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#800]
Currently Mojos are tightly coupled together:

* via Inheritance
* via static methods call chains
* via calling out Maven goals via a `GoalFinder`

The problem is that these goals are not independent anymore and calling out goals directly from other Mojos defeats the Maven Lifecycle and leads to suprising effect (e.g. when these are bound to other lifecycle phases that can lead to call out goals twice)

Instead Mojos should call into (shared) backend services and be used independently.

**Comment by nicolaferraro** [comment]
@rhuss have you already evaluated a strategy like [the one used in surefire](https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L2131-L2145) to avoid multiple executions of the same goals?

**Comment by rhuss** [comment]
No, not yet. The problem indeed is, that we react differently depending on whether a certain goal has been called (see `DependencyEnricher`). If we get rid of this, then I think we are pretty safe now, but its good to keep in mind the code you referenced, so that we can be even more robust e.g. for wired `<executions>` setting or when using forked lifecycles (which I would like to have for `fabric8:build` like in d-m-p to avoid the issue that `mvn package` needs to be called together with `fabric8:build`)

[had to edit the orignal description, because we don't call other goals, but examine which goals has been called and then do different things, which makes the usage quite intransparent]

**Comment by nicolaferraro** [comment]
Yeah, I think it would be useful to allow people running fabric8 goals independently of what they have configured in `<executions>`. Maybe some users do not want to bind `resource` and `build` to the maven default lifecycle, because it slows down the build time.

I've found also the spring-boot generator doing something different (adding the dev-tools libraries) when `fabric8:watch` or `fabric8:watch-spring-boot` are called. Need to find a better way...

**Comment by rhuss** [comment]
We need the sword of Arthur, Excalibur.
