### ISSUE TITLE
Allow for external resources reference; e.g. app tempplates

### ISSUE THREAD

**Issue by alesj** [fabric8io/fabric8-maven-plugin#804]
It would be useful to be able to include external k8s / OpenShift resources.
e.g. a SpringBoot app that requires RHT SSO could simply reference CE team's RHT SSO app template
* https://github.com/jboss-openshift/application-templates/blob/master/sso/sso70-https.json

(and not have to copy paste the resource file -- leave it to the original authors to be properly maintained)

@ro14nd ^^

**Comment by rhuss** [comment]
Yes, I think it makes sense to allow a list of URL in the plugin's configuration so that object definitions can be downloaded on the fly and added to the list of objects to process.

Maybe we should allow also a profile to be used so that these resource could be also enriched.

A suggestion could be:

```xml
<configuration>
  <extra>
     <remote>
        <url>https://github.com/jboss-openshift/application-templates/blob/master/sso/sso70-https.json</url>
        <!-- No enrichment --> 
        <profile>raw</profile>
     </remote>
   </extra>
</configuration>
```

or mabe embedded in the `<resource>` configuration. But the idea should be clear.

If this is given, then the `openshift.yml` should contain these templates, too (so that it can be distributed) along with the artifact. `fabric8:apply` should manage this as any other resource.

An alternative approach (or maybe even in addition) to use fragment files which are named like `sso-external.yml`

and has a content like:

```yml
url: https://github.com/jboss-openshift/application-templates/blob/master/sso/sso70-https.json
```

**Comment by alesj** [comment]
Perhaps fragments files are better approach,
as you then don't need to change the plugin config -- can have the same for all different artifacts.

**Comment by cmoulliard** [comment]
Whenever which approach we decide to adopt, how it be possible to specify the parameters to be used tu customize the application to be created from the template ?

**Comment by rhuss** [comment]
@cmoulliard Sorry, don't get your question. This issue is not about _applying a template_ but getting the template object it into OpenShift by referring to an external source. 

Wdym with _'specify the parameters'_ ?

**Comment by cmoulliard** [comment]
@rhuss The question of @alesj concerns the following point. Is it possible to pass to the f-m-plugin a reference to an openshift template instead of decomposing an openshift template into the corresponding objects as we did [here](https://github.com/obsidian-toaster-quickstarts/secured_rest-springboot/tree/master/sso/src/main/fabric8)
If f-m-p could support this option which is to deploy the openshift template, then we should offer the possibility to set the [parameters](https://github.com/obsidian-toaster-quickstarts/secured_rest-springboot/blob/master/sso/src/main/fabric8/template.yml#L17)

**Comment by rhuss** [comment]
No, there is no way to apply / fill in value for template parameters when doing a `fabric8:apply`. And tbh, this is indeed a different story for which a different issue should be created.

The question will be, from where the values should come from. Maven properties ? standard input ? External property file ? Please open an issue for this, maybe with your preferred way how to provide those values.

**Comment by rhuss** [comment]
Might be still useful, adding it to the backlog.
