### ISSUE TITLE
when OpenShift Templates support namespaces inside resources we should add a NamespaceEnricher

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#882]
we've a use case where we'd like to create a single Template that creates multiple `ProjectRequest` instances and puts `Service` and `DeploymentConfig` resources into different namespaces.

So we'd like to depend on some YAML files and default the namespace they should be installed inside.

Though right now `oc process` strips the namespaces out which limits the usefulness of these templates ;) - but when thats fixed it'll make them pretty handy for setting up environments + tools in a single template

**Comment by jstrachan** [comment]
one thing not in this PR yet is the ability to provide a mapping of names to namespaces; but folks could always do that with multiple mvn modules as a work around

**Comment by rhuss** [comment]
What is a `ProjectRequest` instance ?

**Comment by jstrachan** [comment]
Its all kinda bizarre & I really don't understand the point; but in OpenShift you can't list or view Namespaces; because security, so you can list Projects instead which map 1-1 with Namespaces. Then you usually can't create Projects either; so you have to create a ProjectRequest to make a Project to make a Namespace. Obvious eh! :)

**Comment by jstrachan** [comment]
@rhuss BTW one issue I had when creating this NamespaceEnricher is that it actually needs to enrich dependencies; so I had to explicitly invoke it after the first pass of enrichments: https://github.com/jstrachan/fabric8-maven-plugin/commit/1fea75df214c75f0dc8a9f70ed61500053bca5f9#diff-00c124578b1d9f956274da34bb5c3641

it didn't feel super clean though - I'm sure you won't like it ;). I couldn't figure out why the `NamespaceEnricher` never seemed to see any of the dependencies in the normal enrichment flow - despite being last in the list. Another approach could be a second profile for post processing (after dependencies)?

**Comment by jstrachan** [comment]
here's an example ProjectRequest from a fmp generated Template that effectively makes a few namespaces in a single Template https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/test-pr.yml

**Comment by rhuss** [comment]
> it didn't feel super clean though - I'm sure you won't like it ;). I couldn't figure out why the NamespaceEnricher never seemed to see any of the dependencies in the normal enrichment flow - despite being last in the list. 

You can read my mind (well, was probably not that hard in this case ;-). The reason why its not enriched, is very likely because openshift based dependencies are not added in the `DependencyEnricher` but just [remembered](https://github.com/rhuss/fabric8-maven-plugin/blob/9e9807861c870635fb1b0269413e673c0a3b9304/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DependencyEnricher.java#L137-L137) in a variable which then later is [added](https://github.com/rhuss/fabric8-maven-plugin/blob/9e3dc794621dd903bd440330ba53c350720607a2/core/src/main/java/io/fabric8/maven/core/util/OpenShiftDependencyResources.java#L111-L111) to the list, so they are not subject of further enrichments.

So the hack here is build on top of and because of this openshift-template-dependency hack (which btw came in with this [PR](https://github.com/fabric8io/fabric8-maven-plugin/pull/546/files) which I overlooked first, discovered it three months later and now still struggling to get it straight because so much other stuff has grown around it).

The true solution of this _let's get enrichment straight and properly decoupled_ story is buried in #678 where the generation of kubernetes and openshift objects are completely separated in a 2-phase run (so each enricher can do specific things for kubernetes.yml and/or openshift.yml).

I really would love to tackle this, but we all know these are busy times (but I'm confident I can do it soon in April or so). Piling up the technical debt in the meantime doesn't help, though.

But it's your decision of course.

**Comment by rhuss** [comment]
> Another approach could be a second profile for post processing (after dependencies)?

Yes, if we properly understood why the enrichment didn't work in the first place. With the current solution, it is not possible to disable this NameSpace enricher, if I understood right. Might be ok if this is something everybody needs (but not sure about this).

I'm off for a presentation today (btw, with brand new f-m-p demos ;-) but could have a look tomorrow if you like.

**Comment by jstrachan** [comment]
Agreed. Note that this PR isn't urgent as OpenShift templates are currently broken (it strips out all the namespace metadata ;). I just wanted to put the code somewhere for when we can use Templates and Namespaces.

You're right the dependency enrichment issue is due to the fact that we have both kubernetes and openshift dependencies and we're not properly separating them right now. Today we load the kubernetes ones only and then swizzle them to openshift. We really should have 2 completely separate passes really; that loads, generates + enriches pure kubernetes stuff then another pass that loads, generates & enriches pure openshift dependencies.

**Comment by jstrachan** [comment]
We should probably focus on cleaning up the kubernetes versus openshift dependency/generation/enrichment really; I can imagine us hitting other issues down the road. If that part worked great then the NamespaceEnricher would have been trivial and not require any special post-processing etc

**Comment by rhuss** [comment]
Let's reconsider this when we hit the use case again.
