### ISSUE TITLE
broken CD pipelines on openshift due to changes in behaviour over the ImageStream YAML generation

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#910]
what used to happen was, we'd run the `resource` goal and generate the basic DeploymentConfig / Service stuff into `openshift.yml` then the `build` goal would generate the image stream and add the `ImageStream` into the `openshift.yml` so that we could then rollout the same YAML to other environments as a single simple YAML by applying the `openshift.yml`.

Now in fmp 3.3.x it seems that the image stream is generated to `target/${project.artifactId}-is.yml` which is then never released to nexus nor gets propagated to other environments. 

So when using fabric8 pipelines on OpenShift all deployments break on `staging` and `production` plus a user can never again deploy the app in any other namespace. The image stream would have to be manually copied from the build namespace and cluster by hand.

@ro14nd I'm guessing this was an intentional change of yours? I can imagine you didn't like the 2 phases generating separate parts of the complete YAML ;). I'm just wondering what you think we should do about this? I figured you had a plan in mind so thought I'd ask first before trying to dive in and fix it.  

We *really* want to be able to do CD pipelines with multiple namespaces on openshift ASAP so kinda need a solution.

At a minimum we need the imagestream YAML released into nexus; then a canonical place to find the image stream(s) just like we can look for `openshift.yml` if they must be separate files. Though the easiest thing to do is just put them all in the `openshift.yml` file. The question is how you'd like to do this - bring back the old behaviour or have a new third goal invoked to combine them (but then that seems even more brittle than just having 2 goals?)

@ro14nd thoughts?

**Comment by jstrachan** [comment]
without the ImageStream inside, the generated`openshift.yml` by fmp is kinda pointless - it won't work unless a user first finds the namespace where the build was; finds the imagestream + tag by hand, exports it and re-imports it into the new namespace before the `openshift.yml` is used by a user or pipeline

**Comment by jstrachan** [comment]
Another thing which is also now broken in addition to CD pipelines, `mvn fabric8:deploy` on other namespaces & fabric8-arquillian is the ability to compose apps together like we've been doing for a few years now using maven dependencies; since the ImageStream just lives in `target` - its never released to nexus or included in the jars so it basically just vanishes.

I still don't see any reason to break `openshift.yml` from being useful. If there is a use case for YAML without image streams (I still struggle to understand why that would be useful) , then maybe we need 2 openshift YAMLs? one with and one without the image streams?

I'd at least expect that:

* we release to nexus a YAML for resources and image streams & tags so folks can use stuff via `oc apply`
* we store either a complete YAML in `META-INF/fabric8` or an `openshift.yml` and an `openshift-is.yml`

**Comment by rhuss** [comment]
@jstrachan we had quite some discussion around this (unfortunately you haven't participated in that although pinged several times. not blaming, though, as we are all super busy these days ;-)

* https://github.com/fabric8io/fabric8-maven-plugin/issues/768
* https://github.com/fabric8io/fabric8-maven-plugin/pull/782
* https://github.com/fabric8io/fabric8-maven-plugin/pull/783
* https://issues.jboss.org/browse/OSFUSE-473

My main point is probably best summarised in https://github.com/fabric8io/fabric8-maven-plugin/pull/783#issuecomment-272945513 I also referring there to the CD use case crossing namespace but would hoped there for some more input at that time (please (re?) read that comment). Actually I still believe that including an installation specific imagestream (which includes the sha256 of a very concrete image) in a distributed installation-agnostic artefact feels very wrong (and tbh I think I'm not alone here). But let's discuss this again, you find all my arguments in the referenced issues / PRs. I can repeat them here if required.

I see your point and your use case (as hopefully you also see my points). It was always the challenge for f-m-p to fit all (or at least the productised) use cases. Let's find a solution together on Monday how we get CD back on track again without including imagestreams into openshift.yml for inclusion in an universally distributed jar file.

**Comment by rhuss** [comment]
> Another thing which is also now broken in addition to CD pipelines, mvn fabric8:deploy on other namespaces & fabric8-arquillian is the ability to compose apps together like we've been doing for a few years now using maven dependencies; since the ImageStream just lives in target - its never released to nexus or included in the jars so it basically just vanishes.

Actually this is and was also broken when including the image streams into `openshift.yaml` because this happens after the the jar is build. It happens _by accident_ if you do not a `fabric8:resource` (and no clean) before calling `mvn package`, so that an old openshift-yaml (with maybe an imagestream created by an `fabric8:build`  before) was included in the jar. But this can not be the real solution, or ?

The real problem is a kind of hen-egg issue:

* `openhift.yml` is created before the jar file so that it can be included (with all the benefits like using it as dependencies in an aggregation scenario).
* The image stream are created during a build where the full jar is sent to OpenShift for a binary s2i (remember, the jar already including the openshift.yml). How should this image stream be included into the `openshift.yml` contained in the jar already sent to  OpenShift ?

Doesn't if feel wrong to you, too to change the openshift.yml afterwards so that you end up with to variation of the artefact jar for the same version number ?

Also, let's have a look at the generated image-stream.yml:

```yaml
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fabric8-maven-sample-spring-boot
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: fabric8-maven-sample-spring-boot@sha256:62d4322038535838b3f5d63b04fbfd3c8f2aae42b68db35cba2959f8cb86ee12
        namespace: myproject
      name: latest
```

As you can see this is *clearly specific to the cluster where the build happened* as it references the Docker image with the specific sha1 of the image within the internal registry. That means that the generated jar not only depends where it has been built (its different when created on a different cluster) but only can be **used** on this cluster where it has been built and where the cluster has access to this registry where the image resides.

This defeats clearly the purpose of an Maven artefact which is supposed to be distributed e.g. over Maven central into different environments too. 

Within https://issues.jboss.org/browse/OSFUSE-473 @maschmid and me tried to [solve](https://issues.jboss.org/browse/OSFUSE-473?focusedCommentId=13349108&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13349108) this issue for getting image streams across namespaces by introducing runtime specific yaml files not included in the jar. I don't know whether this fits your use case, but maybe we can adapt this here, too ? Maybe one could distribute this runtime specific yaml file also via Nexus within a cluster ? (e.g. by attaching it as an extra artefact with a classifier)

**Comment by rhuss** [comment]
aAter each build you find the imagestreams created in `target/<name>-is.yml`. As said, maybe we could add this file as an artefact with classified `is` (or `imagestream` to be more verbose) to the build so that it gets uploaded to Nexus, too. We then could add a new goal to f-m-p (e.g. `fabric8:apply-is` or `fabric8:is`) which could download this file and apply it to the current namespace ?

**Comment by rhuss** [comment]
Just added a PR for adding the imagestream descriptor with classified "is" to the build so that they get distributed via a Maven repo on deploy, like this https://oss.sonatype.org/content/repositories/snapshots/io/fabric8/fabric8-maven-sample-spring-boot/3.3-SNAPSHOT/fabric8-maven-sample-spring-boot-3.3-20170410.091643-1-is.yml example.

@jstrachan Is this a step in the right direction and could this be a solution (along with an appropriate apply goal)  for letting the image be referenced in the various CD namespaces ?

**Comment by jstrachan** [comment]
So its kinda hard to keep track on all issues across 200 repos. There are > 2000 open issues across just fabric8io repos at the time of writing (with fabric8io-images / fabric8-ui / fabric8-analytics / fabric8-quickstarts on top of those). I never saw any of those mentions on those issues. I'll review my gmail filters to see if I can get more prominent notifications when I'm mentioned by name on an issue though! 

Maybe next time we're looking at a breaking change its maybe worth spinning up an email on fabric8's mailing list as its really easy to miss github notifications when you get tons of them every day.

I understand your point about the image stream containing cluster-specific information. But thats kinda true of most docker images isn't it? e.g. using a custom docker registry has the same issue - your manifest depends on the cluster/repository that your image is built on. Without using an explicit docker registry am not sure there's a better solution yet than distributing the ImageStreams YAML?

So yeah, maybe we just for now have an `is.yml` file we distribute? We can then go and try fix up `mvn fabric8:deploy`, fabric8-arquillian and the CD pipelines to work with those ImageStreams when on openshift?

**Comment by jstrachan** [comment]
@ro14nd thanks for that PR - that sounds like a nice compromise; we can start fixing up other parts of the fabric8 ecosystem to work with this new approach

**Comment by rhuss** [comment]
> Maybe next time we're looking at a breaking change its maybe worth spinning up an email on fabric8's mailing list as its really easy to miss github notifications when you get tons of them every day.

TBH, I didn't thought about this as a breaking changes as I have the same problem that I can't keep perfectly track of the sheer amount of projects using f-m-p. If I would have been aware of this I would of course pushed even more to get an answer on my questions. And although I mentioned the change on the [mailing list](https://groups.google.com/d/msg/fabric8/5v2NeO_2WR4/cM1416kkDgAJ) it was for sure not prominent enough. Unfortunately our test coverage is not good enough as this change slipped through for two month without actually raising any issue. So we need to be even more communicative, which worked in the past not so badly e.g. when we agreed to remove the implicit service port mapping from 8080 to 80. I will try my very best that this won't happen again.

The first part in distributing the `-is.yml` to the Maven repo is done (via the PR). The second step is now to include this into either `fabric8:apply` or introduce an extra `fabric8:appy-is` which either takes the localse is-file if the repo was used to build the artefact or download it from Nexus if only the resources are created.

@jstrachan But I have a question here, as I do not understand how it could work before: When the deployments in _Testing_ and _Production_ happen, from where do they got the openshift.yml with the image stream included ? Was there a direct fetch from the Maven repo, where the openshift.yml was stored directly as artefact ? (which btw as always different than the openshift.yml included within the jar). Was it `fabric8:apply` which fetched this ? Or was a Jenkins pipeline script who does this ? (which would make sense, as there is no need to checkout the Maven project dir only to apply resource descriptors which were then downloaded). If the latter is the case, maybe we dont even need an extra Maven goal for this.

**Comment by jstrachan** [comment]
@rhuss yeah - its really hard for any of us to grok the full picture (particularly with the various project versus product stuff going on as a layer above all this stuff). I'm hoping post Summit we can get nice automated system testing on our CD infrastructure which can help give better visibility; e.g. when, say, an fmp release breaks some downstream project. I think there's so many inter-related OSS projects now its just too hard to grok what change is really gonna break anything downstream without just testing and reporting those breaks ;). It looks like more and more OSS projects and products will be moving to fabric8 CI / CD so that'll help improve visibility between projects (e.g. as we automate upgrading versions of things more between projects with upstream and downstream breakage reporting).

I've patched the kubernetes-pipeline-plugin in jenkins to hopefully work with the new fmp 3.3.x behaviour.

On the question; previously the local `target/classes/META-INF/fabric8/openshift.yml` was used for Test / Stage / Production rather than from nexus. So now `kubernetesApply()` will look for `target/*-is.yml` and apply that first if on OpenShift

**Comment by jstrachan** [comment]
@rhuss thanks for all your comments & PRs on this issue! 

I think most things are back in working order now (once upstream gets a new release with the latest jenkins stuff) - though I've not had chance to look at composing apps together yet; though luckily when we compose things upstream we use docker hub for images so side-step the ImageStream issue completely ;)

**Comment by rhuss** [comment]
It was an awesome discussion with @jstrachan at that time and highlights again the difficulties to separate application generic information and pure runtime information. Although I think we could still improve here, I like to close this issue for now. RIP :)
