### ISSUE TITLE
Vert.x health enricher does not generate health probes

### ISSUE THREAD

**Issue by SlavoKrupa** [fabric8io/fabric8-maven-plugin#924]
### Description
In newer version of fabric8 maven plugin it seems that Vert.x health enricher does not work. It was working in 3.2.28 release.
* f-m-p version : 3.3.4 or 3.2.31
* Maven version (`mvn -v`) : 3.3.9
* Kubernetes / OpenShift setup and version : minishift 1.0.0
* How to reproduce : run integration tests `mvn clean verify -Popenshift -Dfabric8.maven.plugin.version=3.3.4 -f healthcheck-it/pom.xml` 
* Sample project : https://github.com/SlavoKrupa/vertx-openshift-it/tree/openshift_assistant_refactor in health-check-it

**Comment by SlavoKrupa** [comment]
@cescoffier FYI

**Comment by rhuss** [comment]
Thanks for the report and the sample project. After git bisecting this commit is the culprit: https://github.com/fabric8io/fabric8-maven-plugin/commit/a1d58bbb04fc63ead23b41ffa948d0df89c7cf45 Going to fix this and add a unit test.

**Comment by SlavoKrupa** [comment]
@rhuss Thanks for fast analysis and reply.

**Comment by rhuss** [comment]
Well, in fact its not really a bug. The reason is that the way how `<include>` are handled has been changed to fix another issue. 

Now, if you include, the enricher goes to the front of the list of enrichers. Since we use currently for two tasks, generating default objects and enriching existing objects, we need to create the objects first, which then can be enriched. This is done implicitly, but we are working to separate these phases better via #678 

For now you either omitt the include (but then there is indeed a bug that this enricher was missng in the default profile in `profiles-default.yml`, this will be fixed in the next release), or for the moment its the best to include the `fmp-controller` before the `vertx-health-check`

```xml
<enricher>
    <includes>
        <include>fmp-controller</include>
        <include>vertx-health-check</include>
    </includes>
   ....
</enricher>
```

In the next release you can simply remove all `<includes>` as then the health check is already inserted in the proper position by default.

As said this will be fixed with #678 but this will take a bit since it is a _big_ change. 

Could you live with this workaround ?

**Comment by SlavoKrupa** [comment]
Yeah. I can live with that. I did not investigate, but is there similar issue for `swarm-health-enricher`?

**Comment by rhuss** [comment]
Yes, any real _enricher_ (which means adding something to something existing) needs the objects created with the do enricher. Certain enrichers, which are responsible for creating default objects (mainly `fmp-service` and `fmp-controller`) must run before. However since the `swarm-health-enricher` is already included in the default profile, you do not need any includes at all.

**Comment by SlavoKrupa** [comment]
Can you please point me to where it is defined that `wildfly-swarm-health-check` is included in default profile ?
I checked the file [profiles-default.yaml](https://github.com/fabric8io/fabric8-maven-plugin/blob/bf3284eec1312df18fcfc2a5bb1d11e94d7d0185/plugin/src/main/resources/META-INF/fabric8/profiles-default.yml) and it is not there. I am not sure whether there is another place where it is defined.

**Comment by Ladicek** [comment]
I've submitted https://github.com/fabric8io/fabric8-maven-plugin/pull/930 to add the Swarm health check enricher to the default profile.
