### ISSUE TITLE
ConfigMaps content from external data (fragment/xml config)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#977]
[here's an example](https://github.com/fabric8-quickstarts/spring-boot-webmvc/blob/master/src/main/fabric8/configmap.yml#L4-L7
) of where we embed an `application.properties` file inside a `ConfigMap`. We may want to maintain the contents separately - so its easier to test the file for example (e.g. parse it or use it in a junit test case).

So maybe we could replace this with something like:
```yaml
metadata:
  annotations:
    file-import.maven.fabric8.io/application.properties: ${basedir}/target/test-classes/application.properties
```
which would load the given key `application.properties` from the given local file system file and import it into the generated YAML like this https://github.com/fabric8-quickstarts/spring-boot-webmvc/blob/master/src/main/fabric8/configmap.yml#L4-L7

**Comment by rhuss** [comment]
Agree that this makes much sense to prepare configmaps and secrets (see also #975 ) from files. Instead of using annotations for fragments though (which would have no meaning during runtime), I'd prefer to add an XML configuration for preparing such cm / secrets. It would make the definition of such imports more concise:

```xml
<configuration>
   <resources>
      <configmaps>      
          <cm>
               <!-- Plain entry -->
               <entry>
                    <name>myKey</name>
                     <value>myValue</value>
               </entry>
              <!-- Import with name -->
              <entry>
                    <name>config</name>
                    <file>${basedir}/target/test-classes/application.properties</file>
               </entry>
               <!-- Would import with the filename as key. Or just use an <entry> without name -->
              <import>${basedir}/target/test-classes/application.properties</import>
               .....
          <cm>
      <configmaps>
   </resources>
</configuration>
```

If we would go for support for yaml annotation, I would like then to remove the annotation befire adding it to kubernetes.yml (as it exposed build details which are of no use and maybe even unwanted during deployment time)

**Comment by jstrachan** [comment]
Am happy with the XML and/or annotation approach. I guess the XML approach may be easier to tool one day (IDEs might be smart enough to grok <file> is-a file etc). 

Agreed that if we did go with annotations we should remove the `file-import.maven.fabric8.io/*` annotation during enrichment.

**Comment by yuwzho** [comment]
Agree that the XML configuration is convenient.  But yaml configuration is the standard way to use kubernetes. If the maven tool moves the configuration way to XML from yaml, and builds the yaml fragment when compiling, it is difficult for user migrating to this maven plugin with former kubernetes configuration or background knowledge.

**Is there any way to replace the yaml annotation from maven settings file?**

BTW, I notice the issue #11 , which requests for replacing the yaml annotation with environment variables, is held on more than one year. What is the concern for holding this issue? I ask this question since I think replace yaml annotations with docker secret is similar with environment.

**Comment by jstrachan** [comment]
We can use maven properties in the YAML file fragments which we can then replace (e.g. using the maven resource filtering); so that we can refer to docker image versions or whatnot using maven properties.

When it comes to Secrets I think those should mostly be maintained out of band from applications. i.e. the aim of the fabric8-maven-plugin is to generate an application YAML which can be versioned, shared in public maven repositories or used in Helm chart repositories and then installed on any cluster or namespace; and so have no environment specific data such as Secrets or PVs inside which are highly specific to a particular cluster / namespace / environment installation. 

I can see folks wanting to use a tool like fabric8-maven-plugin to help generate, enrich, combine, process resources to make YAML - but I think Secrets should be handled completely different to the current way we handle resources in fabric8-maven-plugin. e.g. they should always just be generated into, say, `target/fabric8/secrets` and never included in the jars or published to maven repos or included in Helm charts.

**Comment by rhuss** [comment]
> Agree that the XML configuration is convenient. But yaml configuration is the standard way to use kubernetes. If the maven tool moves the configuration way to XML from yaml, and builds the yaml fragment when compiling, it is difficult for user migrating to this maven plugin with former kubernetes configuration or background knowledge.

Well, the extension proposed is by no means a k8s standard (although sharing the same format), so it might make even more difficult to understand what's k8s and what's fmp specific if intermixing features freely. At the end, the fragments are a fmp DSL which looks like k8s syntax. And btw, you can use _both_ together, the XML config syntax + the Yaml fragmetns. They get simply merged together. 

Said that, I think it makes sense to support both.

**Comment by rhuss** [comment]
@jstrachan I agree that Secrets are a runtime aspect much like ImageStreams and must not be distributed within the artefact jar (and via Maven repositories)

wrt to secrets, I think using ~/.m2/settings.xml (see #975)  and applying them on the fly for a fabric8:apply or even with a fabric8:secrets (without generating it into the kubernetes.yaml) might help, if fmp is used as a deployment tool (e.g. for CI / CD) ?

**Comment by rhuss** [comment]
@yuwzho wrt #11 : This issue pre dates the fragment support and was replaced by fragments with enrichers as we have now. tbh I think that #11 can be closed.

As @jstrachan says, you already can use Maven properties within the fragments, which can be also environment variables with the syntax ${env.MY_ENV}. This will be resolved when you create the descriptors, so not sure whether this is of much use for the use case at hand.

**Comment by jstrachan** [comment]
@rhuss agreed - we may want to generate and use Secrets in a separate folder (e.g. `target/fabric8/secrets` and use them when using `mvn fabric8:deploy`)

**Comment by yuwzho** [comment]
@rhuss @jstrachan I get your point. So for the secret things, we can do the following steps. Is that correct?

1. User put the yaml fragment into `src/main/fabric8/secrets` folder as this:

  ```yaml
  data:
      .dockerjsonconfig: {docker.serverid}
  metadata:
      name: dockerregistrykey
  ```

2. Has a goal `mvn fabric8:secret` to generate a yaml secret fragment in `target/fabric8/secrets`

3. When call `mvn fabric8:apply`, also load the yaml file in `target/fabric8/secrets` folder

**Comment by rhuss** [comment]
Something like this or also the XML configuartion as sketched out in https://github.com/fabric8io/fabric8-maven-plugin/issues/977#issuecomment-314037889. 

For the servier id a regular Maven property like `${fabric8.server-config.myServerId}` could be used and all such properties are either created and set brute force from settings.xml before the frament is processed or we might require an intermediate configuration step in pom.xml to declare only the properties which need to be pre-populated.

**Comment by yuwzho** [comment]
@rhuss For the XML configuration, of course user can refer the secret in XML, and then read in the maven parameters can easily generate the yaml file. 

But where is the metadata thing come from? User should specific the name property and whatever properties they like in the metadata.

Need user put these things like XML configuration or just a yaml fragment, and the code merges yaml and XML. If do the merge thing, how to specific which XML segment merge with which yaml fragment?

**Comment by yuwzho** [comment]
I want to split the topic in this thread since we already talked about `config-map`, `secret.generic` and `secret.docker-registry` things. And all of them we talk about XML configuration and yaml fragment

But the XML configuration for secret thing is still need to be discussed as I mentioned in last comment.

<table>
<thead>
<th></th>
<th>Config Map</th>
<th>Secret generic</th>
<th>Secret docker registry</th>
</thead>
<tbody>
<tr>
<td>Yaml</td>
<td>Write the value into property file and refer the file in yaml annotation. As <a href="https://github.com/fabric8io/fabric8-maven-plugin/issues/977#issue-241626681">this issue</a></td>
<td>
similar with docker registry, but the yaml fragment as 
<pre>
data:
    password: ${secret.password}
metadata:
    name: secretkey
</pre>

<p>But which section in maven setting file to save these custom secret key-value pair.</p>
</td>
<td>Write the secret things into maven settings file, and compile it in target place. As <a href="https://github.com/fabric8io/fabric8-maven-plugin/issues/977#issuecomment-314989588">this comment</a></td>
</tr>
<tr>
<td>XML</td>
<td>Configure with pom.xml and property file. As <a href="https://github.com/fabric8io/fabric8-maven-plugin/issues/977#issuecomment-314037889">this comment</a></td>
<td><em>TBD</em></td>
<td><em>TBD</em></td>
</tr>
</tbody>
</table>

**Comment by yuwzho** [comment]
Hi @jstrachan and @rhuss , since we have a project is so urgent need the `docker-registry` secret. We would like to contribute the `docker-registry` secret feature with both Yaml and XML implementation (The last column in the above table).

**Comment by rhuss** [comment]
@yuwzho for the secret could we do it similar like for the ConfigMap with an annotation ? E.g. use a custom annotation instead of a 'magic' property (which would not play nicely with properties replaced by the resource maven plugin) ? This annotation would then be processed, removed and add the proper secret from the registry.

The implementation for the evaluation of annotations in the fragments and the custom processing could probably already easily done by a dedicated Enricher (who has access to the settings.xml, I believe), so that this feature can be easily removed/added or put into profiles like the other enrichers we are using.

wdyt?

we are totally open to pull request and would integrate them (said that, I'm at the moment a quite disconnected from f-m-p development as I'm working in a totally different project right now). But its not only me ;-)

**Comment by rhuss** [comment]
I've seen that this support for external data for config maps and secrets has been added via #1013, so I think we should do something similar for ConfigMaps, too.
